// @flow

import type {Model} from 'sequelize'
import * as graphql from 'graphql'
import {attributeFields} from 'graphql-sequelize'

type Options = {
  cache?: Object,
}

export default function defaultInputType(
  model: Class<Model<any>>,
  options?: Options = {}
): graphql.GraphQLInputObjectType {
  return new graphql.GraphQLInputObjectType({
    name: `Input${model.name}`,
    fields: () => ({
      ...attributeFields(model, {
        allowNull: true,
        ...options,
        exclude: (key: string) => {
          if (model.attributes[key]._autoGenerated) {
            return true
          }
        },
      }),
    })
  })
}

