// @flow

import type {Model} from 'sequelize'
import * as graphql from 'graphql'
import {attributeFields} from 'graphql-sequelize'

type Options = {
  cache?: Object,
  fields?: {
    [name: string]: graphql.GraphQLInputFieldConfig,
  },
}

export function defaultCreateTypeName(model: Class<Model<any>>): string {
  return `Create${model.options.name.singular}`
}

export default function defaultCreateType(
  model: Class<Model<any>>,
  options?: Options = {}
): graphql.GraphQLInputObjectType {
  const {fields = {}, ...attributeFieldsOptions} = options
  return new graphql.GraphQLInputObjectType({
    name: defaultCreateTypeName(model),
    fields: () => ({
      ...attributeFields(model, {
        allowNull: false,
        ...attributeFieldsOptions,
        exclude: (key: string) => {
          if (fields[key] || model.attributes[key].allowNull || model.attributes[key]._autoGenerated) {
            return true
          }
        },
      }),
      ...attributeFields(model, {
        allowNull: true,
        ...attributeFieldsOptions,
        exclude: (key: string) => {
          if (fields[key] || !model.attributes[key].allowNull || model.attributes[key]._autoGenerated) {
            return true
          }
        },
      }),
      ...fields,
    })
  })
}

