// @flow

import type {Model} from 'sequelize'
import * as graphql from 'graphql'
import {attributeFields} from 'graphql-sequelize'

type Options = {
  cache?: Object,
  fields?: {
    [name: string]: graphql.GraphQLInputFieldConfig,
  },
}

export function defaultUpdateTypeName(model: Class<Model<any>>): string {
  return `Update${model.options.name.singular}`
}

export default function defaultUpdateType(
  model: Class<Model<any>>,
  options?: Options = {}
): graphql.GraphQLInputObjectType {
  const {fields = {}, ...attributeFieldsOptions} = options
  return new graphql.GraphQLInputObjectType({
    name: defaultUpdateTypeName(model),
    fields: () => ({
      ...attributeFields(model, {
        allowNull: true,
        ...attributeFieldsOptions,
        exclude: (key: string) => {
          const attr = model.attributes[key]
          if (fields[key] || (attr._autoGenerated && !attr.primaryKey)) {
            return true
          }
        },
      }),
      ...fields,
    })
  })
}

