version: "2"
services:
  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
  redis:
    image: redis:3.2
    ports:
      - 6379:6379
  app:
    image: jcoreio/iron-pi-webapp
    ports:
      - "${PORT}:80"
    environment:
      - ROOT_URL=${ROOT_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
      - redis

