version: "2"
services:
  db:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
  selenium:
    image: selenium/hub:3.8.1-bohrium
    ports:
      - 4444:4444
  chrome:
    image: selenium/node-chrome:3.8.1-bohrium
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_PORT_4444_TCP_ADDR: 'hub'
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_INSTANCES: 3
      NODE_MAX_SESSION: 3
    links:
      - selenium:hub
    extra_hosts:
      - "localhost:192.168.65.1"
  firefox:
    image: selenium/node-firefox:3.8.1-bohrium
    environment:
      HUB_PORT_4444_TCP_ADDR: 'hub'
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_INSTANCES: 3
      NODE_MAX_SESSION: 3
    volumes:
      - /dev/shm:/dev/shm
    links:
      - selenium:hub
    extra_hosts:
      - "localhost:192.168.65.1"
  app:
    image: jcoreio/iron-pi-webapp
    ports:
      - "${PORT}:80"
    environment:
      - ROOT_URL=${ROOT_URL}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

