version: "2"
services:
  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
  redis:
    image: redis:3.2
    ports:
      - 6379:6379
  app:
    image: jcoreio/iron-pi-webapp
    ports:
      - "3000:80"
    environment:
      - ROOT_URL=http://localhost:3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=db
      - DB_USER=root
      - DB_NAME=pasonpower
      - DB_PASSWORD=password
      - DB_MIGRATE=true
      - LOG_GROUP_NAME=battmanDataConsumerProdShart
      - AWS_REGION=us-west-2
    depends_on:
      - db
      - redis

