// flow-typed signature: 27aca2446f790d02556a7f003edc32ea
// flow-typed version: <<STUB>>/async-child-process_v^1.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async-child-process'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'async-child-process' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'async-child-process/lib/childPrinted' {
  declare module.exports: any;
}

declare module 'async-child-process/lib/execAsync' {
  declare module.exports: any;
}

declare module 'async-child-process/lib/index' {
  declare module.exports: any;
}

declare module 'async-child-process/lib/join' {
  declare module.exports: any;
}

declare module 'async-child-process/lib/kill' {
  declare module.exports: any;
}

declare module 'async-child-process/src/childPrinted' {
  declare module.exports: any;
}

declare module 'async-child-process/src/execAsync' {
  declare module.exports: any;
}

declare module 'async-child-process/src/index' {
  declare module.exports: any;
}

declare module 'async-child-process/src/join' {
  declare module.exports: any;
}

declare module 'async-child-process/src/kill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'async-child-process/lib/childPrinted.js' {
  declare module.exports: $Exports<'async-child-process/lib/childPrinted'>;
}
declare module 'async-child-process/lib/execAsync.js' {
  declare module.exports: $Exports<'async-child-process/lib/execAsync'>;
}
declare module 'async-child-process/lib/index.js' {
  declare module.exports: $Exports<'async-child-process/lib/index'>;
}
declare module 'async-child-process/lib/join.js' {
  declare module.exports: $Exports<'async-child-process/lib/join'>;
}
declare module 'async-child-process/lib/kill.js' {
  declare module.exports: $Exports<'async-child-process/lib/kill'>;
}
declare module 'async-child-process/src/childPrinted.js' {
  declare module.exports: $Exports<'async-child-process/src/childPrinted'>;
}
declare module 'async-child-process/src/execAsync.js' {
  declare module.exports: $Exports<'async-child-process/src/execAsync'>;
}
declare module 'async-child-process/src/index.js' {
  declare module.exports: $Exports<'async-child-process/src/index'>;
}
declare module 'async-child-process/src/join.js' {
  declare module.exports: $Exports<'async-child-process/src/join'>;
}
declare module 'async-child-process/src/kill.js' {
  declare module.exports: $Exports<'async-child-process/src/kill'>;
}
