// flow-typed signature: 55e2b364c2a8cc99c59381ea4d867b92
// flow-typed version: <<STUB>>/babel-preset-es2015-node_v^6.1.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2015-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2015-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-es2015-node/index' {
  declare module.exports: $Exports<'babel-preset-es2015-node'>;
}
declare module 'babel-preset-es2015-node/index.js' {
  declare module.exports: $Exports<'babel-preset-es2015-node'>;
}
