// flow-typed signature: 92ad547fc60c4fbe2215c77bf76224db
// flow-typed version: <<STUB>>/babel-plugin-transform-import-commonjs_vhttps://github.com/jedwards1211/babel-plugin-transform-import-commonjs#patch-1-built/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-import-commonjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-import-commonjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-import-commonjs/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-import-commonjs/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-import-commonjs/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-import-commonjs/lib/index'>;
}
declare module 'babel-plugin-transform-import-commonjs/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-import-commonjs/src/index'>;
}
