// flow-typed signature: 181ee0fd4ab72c21f862c26d1ca7b1dc
// flow-typed version: <<STUB>>/bless-webpack-plugin_v^1.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bless-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bless-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'bless-webpack-plugin/index' {
  declare module.exports: $Exports<'bless-webpack-plugin'>;
}
declare module 'bless-webpack-plugin/index.js' {
  declare module.exports: $Exports<'bless-webpack-plugin'>;
}
