// flow-typed signature: e33b5f9ce0977feacc2e2dde86856093
// flow-typed version: <<STUB>>/cardinal-spline-js_v^2.3.6/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cardinal-spline-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cardinal-spline-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cardinal-spline-js/curve_calc' {
  declare module.exports: any;
}

declare module 'cardinal-spline-js/curve_func' {
  declare module.exports: any;
}

declare module 'cardinal-spline-js/curve' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cardinal-spline-js/curve_calc.js' {
  declare module.exports: $Exports<'cardinal-spline-js/curve_calc'>;
}
declare module 'cardinal-spline-js/curve_func.js' {
  declare module.exports: $Exports<'cardinal-spline-js/curve_func'>;
}
declare module 'cardinal-spline-js/curve.js' {
  declare module.exports: $Exports<'cardinal-spline-js/curve'>;
}
