// flow-typed signature: 57dba47c1285f5e2d13a621a52410eb9
// flow-typed version: <<STUB>>/chai-datetime_v^1.5.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai-datetime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai-datetime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chai-datetime/chai-datetime' {
  declare module.exports: any;
}

declare module 'chai-datetime/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chai-datetime/chai-datetime.js' {
  declare module.exports: $Exports<'chai-datetime/chai-datetime'>;
}
declare module 'chai-datetime/test/test.js' {
  declare module.exports: $Exports<'chai-datetime/test/test'>;
}
