// flow-typed signature: 319c3bf5e1dcebf306183ab8fb29b2ac
// flow-typed version: <<STUB>>/child-process-async_v^1.0.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'child-process-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'child-process-async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'child-process-async/child-process-async' {
  declare module.exports: any;
}

declare module 'child-process-async/test/child-process-async' {
  declare module.exports: any;
}

// Filename aliases
declare module 'child-process-async/child-process-async.js' {
  declare module.exports: $Exports<'child-process-async/child-process-async'>;
}
declare module 'child-process-async/test/child-process-async.js' {
  declare module.exports: $Exports<'child-process-async/test/child-process-async'>;
}
