// flow-typed signature: 4fab48787cc80151f3ceeba34eecbd2a
// flow-typed version: <<STUB>>/crater-util_v^1.2.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'crater-util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'crater-util' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'crater-util/lib/asyncScript' {
  declare module.exports: any;
}

declare module 'crater-util/lib/dockerComposePort' {
  declare module.exports: any;
}

declare module 'crater-util/lib/dockerEnv' {
  declare module.exports: any;
}

declare module 'crater-util/lib/exec' {
  declare module.exports: any;
}

declare module 'crater-util/lib/execAsync' {
  declare module.exports: any;
}

declare module 'crater-util/lib/getDockerIP' {
  declare module.exports: any;
}

declare module 'crater-util/lib/getMaxMtime' {
  declare module.exports: any;
}

declare module 'crater-util/lib/isDirectory' {
  declare module.exports: any;
}

declare module 'crater-util/lib/isNewerThan' {
  declare module.exports: any;
}

declare module 'crater-util/lib/kill' {
  declare module.exports: any;
}

declare module 'crater-util/lib/killOnExit' {
  declare module.exports: any;
}

declare module 'crater-util/lib/spawn' {
  declare module.exports: any;
}

declare module 'crater-util/lib/spawnAsync' {
  declare module.exports: any;
}

declare module 'crater-util/src/asyncScript' {
  declare module.exports: any;
}

declare module 'crater-util/src/dockerComposePort' {
  declare module.exports: any;
}

declare module 'crater-util/src/dockerEnv' {
  declare module.exports: any;
}

declare module 'crater-util/src/exec' {
  declare module.exports: any;
}

declare module 'crater-util/src/execAsync' {
  declare module.exports: any;
}

declare module 'crater-util/src/getDockerIP' {
  declare module.exports: any;
}

declare module 'crater-util/src/getMaxMtime' {
  declare module.exports: any;
}

declare module 'crater-util/src/isDirectory' {
  declare module.exports: any;
}

declare module 'crater-util/src/isNewerThan' {
  declare module.exports: any;
}

declare module 'crater-util/src/kill' {
  declare module.exports: any;
}

declare module 'crater-util/src/killOnExit' {
  declare module.exports: any;
}

declare module 'crater-util/src/spawn' {
  declare module.exports: any;
}

declare module 'crater-util/src/spawnAsync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'crater-util/lib/asyncScript.js' {
  declare module.exports: $Exports<'crater-util/lib/asyncScript'>;
}
declare module 'crater-util/lib/dockerComposePort.js' {
  declare module.exports: $Exports<'crater-util/lib/dockerComposePort'>;
}
declare module 'crater-util/lib/dockerEnv.js' {
  declare module.exports: $Exports<'crater-util/lib/dockerEnv'>;
}
declare module 'crater-util/lib/exec.js' {
  declare module.exports: $Exports<'crater-util/lib/exec'>;
}
declare module 'crater-util/lib/execAsync.js' {
  declare module.exports: $Exports<'crater-util/lib/execAsync'>;
}
declare module 'crater-util/lib/getDockerIP.js' {
  declare module.exports: $Exports<'crater-util/lib/getDockerIP'>;
}
declare module 'crater-util/lib/getMaxMtime.js' {
  declare module.exports: $Exports<'crater-util/lib/getMaxMtime'>;
}
declare module 'crater-util/lib/isDirectory.js' {
  declare module.exports: $Exports<'crater-util/lib/isDirectory'>;
}
declare module 'crater-util/lib/isNewerThan.js' {
  declare module.exports: $Exports<'crater-util/lib/isNewerThan'>;
}
declare module 'crater-util/lib/kill.js' {
  declare module.exports: $Exports<'crater-util/lib/kill'>;
}
declare module 'crater-util/lib/killOnExit.js' {
  declare module.exports: $Exports<'crater-util/lib/killOnExit'>;
}
declare module 'crater-util/lib/spawn.js' {
  declare module.exports: $Exports<'crater-util/lib/spawn'>;
}
declare module 'crater-util/lib/spawnAsync.js' {
  declare module.exports: $Exports<'crater-util/lib/spawnAsync'>;
}
declare module 'crater-util/src/asyncScript.js' {
  declare module.exports: $Exports<'crater-util/src/asyncScript'>;
}
declare module 'crater-util/src/dockerComposePort.js' {
  declare module.exports: $Exports<'crater-util/src/dockerComposePort'>;
}
declare module 'crater-util/src/dockerEnv.js' {
  declare module.exports: $Exports<'crater-util/src/dockerEnv'>;
}
declare module 'crater-util/src/exec.js' {
  declare module.exports: $Exports<'crater-util/src/exec'>;
}
declare module 'crater-util/src/execAsync.js' {
  declare module.exports: $Exports<'crater-util/src/execAsync'>;
}
declare module 'crater-util/src/getDockerIP.js' {
  declare module.exports: $Exports<'crater-util/src/getDockerIP'>;
}
declare module 'crater-util/src/getMaxMtime.js' {
  declare module.exports: $Exports<'crater-util/src/getMaxMtime'>;
}
declare module 'crater-util/src/isDirectory.js' {
  declare module.exports: $Exports<'crater-util/src/isDirectory'>;
}
declare module 'crater-util/src/isNewerThan.js' {
  declare module.exports: $Exports<'crater-util/src/isNewerThan'>;
}
declare module 'crater-util/src/kill.js' {
  declare module.exports: $Exports<'crater-util/src/kill'>;
}
declare module 'crater-util/src/killOnExit.js' {
  declare module.exports: $Exports<'crater-util/src/killOnExit'>;
}
declare module 'crater-util/src/spawn.js' {
  declare module.exports: $Exports<'crater-util/src/spawn'>;
}
declare module 'crater-util/src/spawnAsync.js' {
  declare module.exports: $Exports<'crater-util/src/spawnAsync'>;
}
