// flow-typed signature: a4ca650e129e15bf949c6230ab14610d
// flow-typed version: <<STUB>>/csv-write-stream_v^2.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csv-write-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csv-write-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csv-write-stream/bench' {
  declare module.exports: any;
}

declare module 'csv-write-stream/cli' {
  declare module.exports: any;
}

declare module 'csv-write-stream/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'csv-write-stream/bench.js' {
  declare module.exports: $Exports<'csv-write-stream/bench'>;
}
declare module 'csv-write-stream/cli.js' {
  declare module.exports: $Exports<'csv-write-stream/cli'>;
}
declare module 'csv-write-stream/index' {
  declare module.exports: $Exports<'csv-write-stream'>;
}
declare module 'csv-write-stream/index.js' {
  declare module.exports: $Exports<'csv-write-stream'>;
}
declare module 'csv-write-stream/test.js' {
  declare module.exports: $Exports<'csv-write-stream/test'>;
}
