// flow-typed signature: 69e42c844b26d6a55a32d8becadda9f2
// flow-typed version: <<STUB>>/faye-websocket_v^0.11.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'faye-websocket'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'faye-websocket' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'faye-websocket/examples/autobahn_client' {
  declare module.exports: any;
}

declare module 'faye-websocket/examples/client' {
  declare module.exports: any;
}

declare module 'faye-websocket/examples/proxy_server' {
  declare module.exports: any;
}

declare module 'faye-websocket/examples/server' {
  declare module.exports: any;
}

declare module 'faye-websocket/lib/faye/eventsource' {
  declare module.exports: any;
}

declare module 'faye-websocket/lib/faye/websocket' {
  declare module.exports: any;
}

declare module 'faye-websocket/lib/faye/websocket/api' {
  declare module.exports: any;
}

declare module 'faye-websocket/lib/faye/websocket/api/event_target' {
  declare module.exports: any;
}

declare module 'faye-websocket/lib/faye/websocket/api/event' {
  declare module.exports: any;
}

declare module 'faye-websocket/lib/faye/websocket/client' {
  declare module.exports: any;
}

// Filename aliases
declare module 'faye-websocket/examples/autobahn_client.js' {
  declare module.exports: $Exports<'faye-websocket/examples/autobahn_client'>;
}
declare module 'faye-websocket/examples/client.js' {
  declare module.exports: $Exports<'faye-websocket/examples/client'>;
}
declare module 'faye-websocket/examples/proxy_server.js' {
  declare module.exports: $Exports<'faye-websocket/examples/proxy_server'>;
}
declare module 'faye-websocket/examples/server.js' {
  declare module.exports: $Exports<'faye-websocket/examples/server'>;
}
declare module 'faye-websocket/lib/faye/eventsource.js' {
  declare module.exports: $Exports<'faye-websocket/lib/faye/eventsource'>;
}
declare module 'faye-websocket/lib/faye/websocket.js' {
  declare module.exports: $Exports<'faye-websocket/lib/faye/websocket'>;
}
declare module 'faye-websocket/lib/faye/websocket/api.js' {
  declare module.exports: $Exports<'faye-websocket/lib/faye/websocket/api'>;
}
declare module 'faye-websocket/lib/faye/websocket/api/event_target.js' {
  declare module.exports: $Exports<'faye-websocket/lib/faye/websocket/api/event_target'>;
}
declare module 'faye-websocket/lib/faye/websocket/api/event.js' {
  declare module.exports: $Exports<'faye-websocket/lib/faye/websocket/api/event'>;
}
declare module 'faye-websocket/lib/faye/websocket/client.js' {
  declare module.exports: $Exports<'faye-websocket/lib/faye/websocket/client'>;
}
