// flow-typed signature: bd33b58edf8ab622e589933f6cd2e486
// flow-typed version: <<STUB>>/graphql-sequelize_v^5.6.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-sequelize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-sequelize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-sequelize/lib/argsToFindOptions' {
  declare module.exports: any;
}

declare module 'graphql-sequelize/lib/attributeFields' {
  declare module.exports: any;
}

declare module 'graphql-sequelize/lib/base64' {
  declare module.exports: any;
}

declare module 'graphql-sequelize/lib/defaultArgs' {
  declare module.exports: any;
}

declare module 'graphql-sequelize/lib/defaultListArgs' {
  declare module.exports: any;
}

declare module 'graphql-sequelize/lib/index' {
  declare module.exports: any;
}

declare module 'graphql-sequelize/lib/relay' {
  declare module.exports: any;
}

declare module 'graphql-sequelize/lib/replaceWhereOperators' {
  declare module.exports: any;
}

declare module 'graphql-sequelize/lib/resolver' {
  declare module.exports: any;
}

declare module 'graphql-sequelize/lib/simplifyAST' {
  declare module.exports: any;
}

declare module 'graphql-sequelize/lib/typeMapper' {
  declare module.exports: any;
}

declare module 'graphql-sequelize/lib/types/jsonType' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-sequelize/lib/argsToFindOptions.js' {
  declare module.exports: $Exports<'graphql-sequelize/lib/argsToFindOptions'>;
}
declare module 'graphql-sequelize/lib/attributeFields.js' {
  declare module.exports: $Exports<'graphql-sequelize/lib/attributeFields'>;
}
declare module 'graphql-sequelize/lib/base64.js' {
  declare module.exports: $Exports<'graphql-sequelize/lib/base64'>;
}
declare module 'graphql-sequelize/lib/defaultArgs.js' {
  declare module.exports: $Exports<'graphql-sequelize/lib/defaultArgs'>;
}
declare module 'graphql-sequelize/lib/defaultListArgs.js' {
  declare module.exports: $Exports<'graphql-sequelize/lib/defaultListArgs'>;
}
declare module 'graphql-sequelize/lib/index.js' {
  declare module.exports: $Exports<'graphql-sequelize/lib/index'>;
}
declare module 'graphql-sequelize/lib/relay.js' {
  declare module.exports: $Exports<'graphql-sequelize/lib/relay'>;
}
declare module 'graphql-sequelize/lib/replaceWhereOperators.js' {
  declare module.exports: $Exports<'graphql-sequelize/lib/replaceWhereOperators'>;
}
declare module 'graphql-sequelize/lib/resolver.js' {
  declare module.exports: $Exports<'graphql-sequelize/lib/resolver'>;
}
declare module 'graphql-sequelize/lib/simplifyAST.js' {
  declare module.exports: $Exports<'graphql-sequelize/lib/simplifyAST'>;
}
declare module 'graphql-sequelize/lib/typeMapper.js' {
  declare module.exports: $Exports<'graphql-sequelize/lib/typeMapper'>;
}
declare module 'graphql-sequelize/lib/types/jsonType.js' {
  declare module.exports: $Exports<'graphql-sequelize/lib/types/jsonType'>;
}
