// flow-typed signature: 1d4eab7553dd99cce88a3e391788a1fc
// flow-typed version: <<STUB>>/jschardet_v^1.5.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jschardet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jschardet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jschardet/dist/jschardet' {
  declare module.exports: any;
}

declare module 'jschardet/dist/jschardet.min' {
  declare module.exports: any;
}

declare module 'jschardet/src/big5freq' {
  declare module.exports: any;
}

declare module 'jschardet/src/big5prober' {
  declare module.exports: any;
}

declare module 'jschardet/src/chardistribution' {
  declare module.exports: any;
}

declare module 'jschardet/src/charsetgroupprober' {
  declare module.exports: any;
}

declare module 'jschardet/src/charsetprober' {
  declare module.exports: any;
}

declare module 'jschardet/src/codingstatemachine' {
  declare module.exports: any;
}

declare module 'jschardet/src/constants' {
  declare module.exports: any;
}

declare module 'jschardet/src/escprober' {
  declare module.exports: any;
}

declare module 'jschardet/src/escsm' {
  declare module.exports: any;
}

declare module 'jschardet/src/eucjpprober' {
  declare module.exports: any;
}

declare module 'jschardet/src/euckrfreq' {
  declare module.exports: any;
}

declare module 'jschardet/src/euckrprober' {
  declare module.exports: any;
}

declare module 'jschardet/src/euctwfreq' {
  declare module.exports: any;
}

declare module 'jschardet/src/euctwprober' {
  declare module.exports: any;
}

declare module 'jschardet/src/gb2312freq' {
  declare module.exports: any;
}

declare module 'jschardet/src/gb2312prober' {
  declare module.exports: any;
}

declare module 'jschardet/src/hebrewprober' {
  declare module.exports: any;
}

declare module 'jschardet/src/index' {
  declare module.exports: any;
}

declare module 'jschardet/src/init' {
  declare module.exports: any;
}

declare module 'jschardet/src/jisfreq' {
  declare module.exports: any;
}

declare module 'jschardet/src/jpcntx' {
  declare module.exports: any;
}

declare module 'jschardet/src/langbulgarianmodel' {
  declare module.exports: any;
}

declare module 'jschardet/src/langcyrillicmodel' {
  declare module.exports: any;
}

declare module 'jschardet/src/langgreekmodel' {
  declare module.exports: any;
}

declare module 'jschardet/src/langhebrewmodel' {
  declare module.exports: any;
}

declare module 'jschardet/src/langhungarianmodel' {
  declare module.exports: any;
}

declare module 'jschardet/src/langthaimodel' {
  declare module.exports: any;
}

declare module 'jschardet/src/latin1prober' {
  declare module.exports: any;
}

declare module 'jschardet/src/mbcharsetprober' {
  declare module.exports: any;
}

declare module 'jschardet/src/mbcsgroupprober' {
  declare module.exports: any;
}

declare module 'jschardet/src/mbcssm' {
  declare module.exports: any;
}

declare module 'jschardet/src/sbcharsetprober' {
  declare module.exports: any;
}

declare module 'jschardet/src/sbcsgroupprober' {
  declare module.exports: any;
}

declare module 'jschardet/src/sjisprober' {
  declare module.exports: any;
}

declare module 'jschardet/src/universaldetector' {
  declare module.exports: any;
}

declare module 'jschardet/src/utf8prober' {
  declare module.exports: any;
}

declare module 'jschardet/tests/jschardet' {
  declare module.exports: any;
}

declare module 'jschardet/tests/qunit/qunit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jschardet/dist/jschardet.js' {
  declare module.exports: $Exports<'jschardet/dist/jschardet'>;
}
declare module 'jschardet/dist/jschardet.min.js' {
  declare module.exports: $Exports<'jschardet/dist/jschardet.min'>;
}
declare module 'jschardet/index' {
  declare module.exports: $Exports<'jschardet'>;
}
declare module 'jschardet/index.js' {
  declare module.exports: $Exports<'jschardet'>;
}
declare module 'jschardet/src/big5freq.js' {
  declare module.exports: $Exports<'jschardet/src/big5freq'>;
}
declare module 'jschardet/src/big5prober.js' {
  declare module.exports: $Exports<'jschardet/src/big5prober'>;
}
declare module 'jschardet/src/chardistribution.js' {
  declare module.exports: $Exports<'jschardet/src/chardistribution'>;
}
declare module 'jschardet/src/charsetgroupprober.js' {
  declare module.exports: $Exports<'jschardet/src/charsetgroupprober'>;
}
declare module 'jschardet/src/charsetprober.js' {
  declare module.exports: $Exports<'jschardet/src/charsetprober'>;
}
declare module 'jschardet/src/codingstatemachine.js' {
  declare module.exports: $Exports<'jschardet/src/codingstatemachine'>;
}
declare module 'jschardet/src/constants.js' {
  declare module.exports: $Exports<'jschardet/src/constants'>;
}
declare module 'jschardet/src/escprober.js' {
  declare module.exports: $Exports<'jschardet/src/escprober'>;
}
declare module 'jschardet/src/escsm.js' {
  declare module.exports: $Exports<'jschardet/src/escsm'>;
}
declare module 'jschardet/src/eucjpprober.js' {
  declare module.exports: $Exports<'jschardet/src/eucjpprober'>;
}
declare module 'jschardet/src/euckrfreq.js' {
  declare module.exports: $Exports<'jschardet/src/euckrfreq'>;
}
declare module 'jschardet/src/euckrprober.js' {
  declare module.exports: $Exports<'jschardet/src/euckrprober'>;
}
declare module 'jschardet/src/euctwfreq.js' {
  declare module.exports: $Exports<'jschardet/src/euctwfreq'>;
}
declare module 'jschardet/src/euctwprober.js' {
  declare module.exports: $Exports<'jschardet/src/euctwprober'>;
}
declare module 'jschardet/src/gb2312freq.js' {
  declare module.exports: $Exports<'jschardet/src/gb2312freq'>;
}
declare module 'jschardet/src/gb2312prober.js' {
  declare module.exports: $Exports<'jschardet/src/gb2312prober'>;
}
declare module 'jschardet/src/hebrewprober.js' {
  declare module.exports: $Exports<'jschardet/src/hebrewprober'>;
}
declare module 'jschardet/src/index.js' {
  declare module.exports: $Exports<'jschardet/src/index'>;
}
declare module 'jschardet/src/init.js' {
  declare module.exports: $Exports<'jschardet/src/init'>;
}
declare module 'jschardet/src/jisfreq.js' {
  declare module.exports: $Exports<'jschardet/src/jisfreq'>;
}
declare module 'jschardet/src/jpcntx.js' {
  declare module.exports: $Exports<'jschardet/src/jpcntx'>;
}
declare module 'jschardet/src/langbulgarianmodel.js' {
  declare module.exports: $Exports<'jschardet/src/langbulgarianmodel'>;
}
declare module 'jschardet/src/langcyrillicmodel.js' {
  declare module.exports: $Exports<'jschardet/src/langcyrillicmodel'>;
}
declare module 'jschardet/src/langgreekmodel.js' {
  declare module.exports: $Exports<'jschardet/src/langgreekmodel'>;
}
declare module 'jschardet/src/langhebrewmodel.js' {
  declare module.exports: $Exports<'jschardet/src/langhebrewmodel'>;
}
declare module 'jschardet/src/langhungarianmodel.js' {
  declare module.exports: $Exports<'jschardet/src/langhungarianmodel'>;
}
declare module 'jschardet/src/langthaimodel.js' {
  declare module.exports: $Exports<'jschardet/src/langthaimodel'>;
}
declare module 'jschardet/src/latin1prober.js' {
  declare module.exports: $Exports<'jschardet/src/latin1prober'>;
}
declare module 'jschardet/src/mbcharsetprober.js' {
  declare module.exports: $Exports<'jschardet/src/mbcharsetprober'>;
}
declare module 'jschardet/src/mbcsgroupprober.js' {
  declare module.exports: $Exports<'jschardet/src/mbcsgroupprober'>;
}
declare module 'jschardet/src/mbcssm.js' {
  declare module.exports: $Exports<'jschardet/src/mbcssm'>;
}
declare module 'jschardet/src/sbcharsetprober.js' {
  declare module.exports: $Exports<'jschardet/src/sbcharsetprober'>;
}
declare module 'jschardet/src/sbcsgroupprober.js' {
  declare module.exports: $Exports<'jschardet/src/sbcsgroupprober'>;
}
declare module 'jschardet/src/sjisprober.js' {
  declare module.exports: $Exports<'jschardet/src/sjisprober'>;
}
declare module 'jschardet/src/universaldetector.js' {
  declare module.exports: $Exports<'jschardet/src/universaldetector'>;
}
declare module 'jschardet/src/utf8prober.js' {
  declare module.exports: $Exports<'jschardet/src/utf8prober'>;
}
declare module 'jschardet/tests/jschardet.js' {
  declare module.exports: $Exports<'jschardet/tests/jschardet'>;
}
declare module 'jschardet/tests/qunit/qunit.js' {
  declare module.exports: $Exports<'jschardet/tests/qunit/qunit'>;
}
