// flow-typed signature: 1efaca754f1be38fc581ac0b94530979
// flow-typed version: <<STUB>>/jss-expand_v^5.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jss-expand'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jss-expand' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jss-expand/benchmark/integration/arrays' {
  declare module.exports: any;
}

declare module 'jss-expand/benchmark/integration/bootstrap' {
  declare module.exports: any;
}

declare module 'jss-expand/benchmark/integration/sheet' {
  declare module.exports: any;
}

declare module 'jss-expand/dist/jss-expand' {
  declare module.exports: any;
}

declare module 'jss-expand/dist/jss-expand.min' {
  declare module.exports: any;
}

declare module 'jss-expand/karma.conf' {
  declare module.exports: any;
}

declare module 'jss-expand/lib/index' {
  declare module.exports: any;
}

declare module 'jss-expand/lib/index.test' {
  declare module.exports: any;
}

declare module 'jss-expand/lib/props' {
  declare module.exports: any;
}

declare module 'jss-expand/tests.webpack' {
  declare module.exports: any;
}

declare module 'jss-expand/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jss-expand/benchmark/integration/arrays.js' {
  declare module.exports: $Exports<'jss-expand/benchmark/integration/arrays'>;
}
declare module 'jss-expand/benchmark/integration/bootstrap.js' {
  declare module.exports: $Exports<'jss-expand/benchmark/integration/bootstrap'>;
}
declare module 'jss-expand/benchmark/integration/sheet.js' {
  declare module.exports: $Exports<'jss-expand/benchmark/integration/sheet'>;
}
declare module 'jss-expand/dist/jss-expand.js' {
  declare module.exports: $Exports<'jss-expand/dist/jss-expand'>;
}
declare module 'jss-expand/dist/jss-expand.min.js' {
  declare module.exports: $Exports<'jss-expand/dist/jss-expand.min'>;
}
declare module 'jss-expand/karma.conf.js' {
  declare module.exports: $Exports<'jss-expand/karma.conf'>;
}
declare module 'jss-expand/lib/index.js' {
  declare module.exports: $Exports<'jss-expand/lib/index'>;
}
declare module 'jss-expand/lib/index.test.js' {
  declare module.exports: $Exports<'jss-expand/lib/index.test'>;
}
declare module 'jss-expand/lib/props.js' {
  declare module.exports: $Exports<'jss-expand/lib/props'>;
}
declare module 'jss-expand/tests.webpack.js' {
  declare module.exports: $Exports<'jss-expand/tests.webpack'>;
}
declare module 'jss-expand/webpack.config.js' {
  declare module.exports: $Exports<'jss-expand/webpack.config'>;
}
