// flow-typed signature: 2bfbbe6b2363ed57d6a7b3cbf03fd6cf
// flow-typed version: <<STUB>>/mindfront-redux-utils-immutable_v^1.3.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mindfront-redux-utils-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mindfront-redux-utils-immutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mindfront-redux-utils-immutable/lib/combineReducers' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils-immutable/lib/index' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils-immutable/lib/subpathReducer' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils-immutable/src/combineReducers' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils-immutable/src/index' {
  declare module.exports: any;
}

declare module 'mindfront-redux-utils-immutable/src/subpathReducer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mindfront-redux-utils-immutable/lib/combineReducers.js' {
  declare module.exports: $Exports<'mindfront-redux-utils-immutable/lib/combineReducers'>;
}
declare module 'mindfront-redux-utils-immutable/lib/index.js' {
  declare module.exports: $Exports<'mindfront-redux-utils-immutable/lib/index'>;
}
declare module 'mindfront-redux-utils-immutable/lib/subpathReducer.js' {
  declare module.exports: $Exports<'mindfront-redux-utils-immutable/lib/subpathReducer'>;
}
declare module 'mindfront-redux-utils-immutable/src/combineReducers.js' {
  declare module.exports: $Exports<'mindfront-redux-utils-immutable/src/combineReducers'>;
}
declare module 'mindfront-redux-utils-immutable/src/index.js' {
  declare module.exports: $Exports<'mindfront-redux-utils-immutable/src/index'>;
}
declare module 'mindfront-redux-utils-immutable/src/subpathReducer.js' {
  declare module.exports: $Exports<'mindfront-redux-utils-immutable/src/subpathReducer'>;
}
