// flow-typed signature: 271f88369b57c1149cd35e9c9e248817
// flow-typed version: <<STUB>>/moment-parseformat_v^2.2.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment-parseformat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moment-parseformat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'moment-parseformat/dist/moment-parseformat' {
  declare module.exports: any;
}

declare module 'moment-parseformat/lib/parseformat' {
  declare module.exports: any;
}

// Filename aliases
declare module 'moment-parseformat/dist/moment-parseformat.js' {
  declare module.exports: $Exports<'moment-parseformat/dist/moment-parseformat'>;
}
declare module 'moment-parseformat/index' {
  declare module.exports: $Exports<'moment-parseformat'>;
}
declare module 'moment-parseformat/index.js' {
  declare module.exports: $Exports<'moment-parseformat'>;
}
declare module 'moment-parseformat/lib/parseformat.js' {
  declare module.exports: $Exports<'moment-parseformat/lib/parseformat'>;
}
