// flow-typed signature: 5a3a261bcd8d3f01527e3017665856ae
// flow-typed version: <<STUB>>/pubsub-js_v^1.5.4/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pubsub-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pubsub-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pubsub-js/autolint' {
  declare module.exports: any;
}

declare module 'pubsub-js/Gruntfile' {
  declare module.exports: any;
}

declare module 'pubsub-js/iframe/pubsub-bridge' {
  declare module.exports: any;
}

declare module 'pubsub-js/lib/jquery-1.7.2' {
  declare module.exports: any;
}

declare module 'pubsub-js/src/pubsub' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/buster' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/helper' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/test-bug-9' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/test-clearSubscriptions' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/test-hierarchical-addressing' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/test-issue-54' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/test-jquery-integration' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/test-publish' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/test-subscribe' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/test-unsubscribe' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pubsub-js/autolint.js' {
  declare module.exports: $Exports<'pubsub-js/autolint'>;
}
declare module 'pubsub-js/Gruntfile.js' {
  declare module.exports: $Exports<'pubsub-js/Gruntfile'>;
}
declare module 'pubsub-js/iframe/pubsub-bridge.js' {
  declare module.exports: $Exports<'pubsub-js/iframe/pubsub-bridge'>;
}
declare module 'pubsub-js/lib/jquery-1.7.2.js' {
  declare module.exports: $Exports<'pubsub-js/lib/jquery-1.7.2'>;
}
declare module 'pubsub-js/src/pubsub.js' {
  declare module.exports: $Exports<'pubsub-js/src/pubsub'>;
}
declare module 'pubsub-js/test/buster.js' {
  declare module.exports: $Exports<'pubsub-js/test/buster'>;
}
declare module 'pubsub-js/test/helper.js' {
  declare module.exports: $Exports<'pubsub-js/test/helper'>;
}
declare module 'pubsub-js/test/test-bug-9.js' {
  declare module.exports: $Exports<'pubsub-js/test/test-bug-9'>;
}
declare module 'pubsub-js/test/test-clearSubscriptions.js' {
  declare module.exports: $Exports<'pubsub-js/test/test-clearSubscriptions'>;
}
declare module 'pubsub-js/test/test-hierarchical-addressing.js' {
  declare module.exports: $Exports<'pubsub-js/test/test-hierarchical-addressing'>;
}
declare module 'pubsub-js/test/test-issue-54.js' {
  declare module.exports: $Exports<'pubsub-js/test/test-issue-54'>;
}
declare module 'pubsub-js/test/test-jquery-integration.js' {
  declare module.exports: $Exports<'pubsub-js/test/test-jquery-integration'>;
}
declare module 'pubsub-js/test/test-publish.js' {
  declare module.exports: $Exports<'pubsub-js/test/test-publish'>;
}
declare module 'pubsub-js/test/test-subscribe.js' {
  declare module.exports: $Exports<'pubsub-js/test/test-subscribe'>;
}
declare module 'pubsub-js/test/test-unsubscribe.js' {
  declare module.exports: $Exports<'pubsub-js/test/test-unsubscribe'>;
}
