// flow-typed signature: 23db506915bcc4addf8c41c0e7dec8f0
// flow-typed version: <<STUB>>/randomcolor_v^0.4.4/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'randomcolor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'randomcolor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'randomcolor/demo/build' {
  declare module.exports: any;
}

declare module 'randomcolor/demo/tests' {
  declare module.exports: any;
}

declare module 'randomcolor/randomColor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'randomcolor/demo/build.js' {
  declare module.exports: $Exports<'randomcolor/demo/build'>;
}
declare module 'randomcolor/demo/tests.js' {
  declare module.exports: $Exports<'randomcolor/demo/tests'>;
}
declare module 'randomcolor/randomColor.js' {
  declare module.exports: $Exports<'randomcolor/randomColor'>;
}
