// flow-typed signature: 5aa843978692730f543407a733f4c543
// flow-typed version: <<STUB>>/react-router-drilldown_v^2.0.4/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-drilldown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-drilldown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-drilldown/flow-typed/npm/@jedwards1211/eslint-config-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/@jedwards1211/eslint-config-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/@kadira/storybook_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/babel-plugin-flow-react-proptypes_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/babel-plugin-istanbul_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/babel-plugin-transform-react-constant-elements_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/babel-preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/babel-preset-stage-1_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/babel-register_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/babel-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/chai_v3.5.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/copy_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/coveralls_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/css-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/enzyme_v3.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/eslint-watch_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/flow-watch_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/inline-style-prefixer_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/istanbul_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/jsdom_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/jsdom-global_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/lodash.size_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/mocha_v3.1.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/nyc_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/prop-types_v15.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/react-hot-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/react-router_v4.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/react-router-dom_v4.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/react-test-renderer_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/react-transition-context_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/rimraf_v2.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/semantic-release_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/sinon_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/style-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/validate-commit-msg_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/lib/index' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/lib/withTransitionContext' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/src/index' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/src/withTransitionContext' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-drilldown/flow-typed/npm/@jedwards1211/eslint-config-flow_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/@jedwards1211/eslint-config-flow_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/@jedwards1211/eslint-config-react_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/@jedwards1211/eslint-config-react_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/@kadira/storybook_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/@kadira/storybook_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/babel-plugin-flow-react-proptypes_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/babel-plugin-flow-react-proptypes_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/babel-plugin-istanbul_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/babel-plugin-istanbul_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/babel-plugin-transform-react-constant-elements_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/babel-plugin-transform-react-constant-elements_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/babel-preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/babel-preset-flow_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/babel-preset-stage-1_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/babel-preset-stage-1_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/babel-register_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/babel-register_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/babel-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/babel-runtime_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/chai_v3.5.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/chai_v3.5.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/copy_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/copy_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/coveralls_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/coveralls_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/css-loader_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/css-loader_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/enzyme_v3.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/enzyme_v3.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/eslint-watch_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/eslint-watch_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/flow-watch_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/flow-watch_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/husky_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/inline-style-prefixer_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/inline-style-prefixer_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/istanbul_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/istanbul_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/jsdom_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/jsdom_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/jsdom-global_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/jsdom-global_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/lodash.size_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/lodash.size_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/mocha_v3.1.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/mocha_v3.1.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/nyc_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/nyc_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/prop-types_v15.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/prop-types_v15.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/react-hot-loader_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/react-hot-loader_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/react-router_v4.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/react-router_v4.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/react-router-dom_v4.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/react-router-dom_v4.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/react-test-renderer_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/react-test-renderer_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/react-transition-context_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/react-transition-context_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/rimraf_v2.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/rimraf_v2.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/semantic-release_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/semantic-release_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/sinon_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/sinon_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/style-loader_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/style-loader_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/validate-commit-msg_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/validate-commit-msg_vx.x.x'>;
}
declare module 'react-router-drilldown/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'react-router-drilldown/flow-typed/npm/webpack_vx.x.x'>;
}
declare module 'react-router-drilldown/lib/index.js' {
  declare module.exports: $Exports<'react-router-drilldown/lib/index'>;
}
declare module 'react-router-drilldown/lib/withTransitionContext.js' {
  declare module.exports: $Exports<'react-router-drilldown/lib/withTransitionContext'>;
}
declare module 'react-router-drilldown/src/index.js' {
  declare module.exports: $Exports<'react-router-drilldown/src/index'>;
}
declare module 'react-router-drilldown/src/withTransitionContext.js' {
  declare module.exports: $Exports<'react-router-drilldown/src/withTransitionContext'>;
}
