// flow-typed signature: 05ae0ff0e28503eadd935cda82e1ea08
// flow-typed version: <<STUB>>/react-transition-context_v^1.0.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-transition-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-transition-context' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-transition-context/lib/index' {
  declare module.exports: any;
}

declare module 'react-transition-context/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-transition-context/lib/index.js' {
  declare module.exports: $Exports<'react-transition-context/lib/index'>;
}
declare module 'react-transition-context/src/index.js' {
  declare module.exports: $Exports<'react-transition-context/src/index'>;
}
