// flow-typed signature: 4bbf734c9eddda00bcb57392190ad79c
// flow-typed version: <<STUB>>/react-router-drilldown_v^2.0.3/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-drilldown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-drilldown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-drilldown/lib/index' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/lib/withTransitionContext' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/src/index' {
  declare module.exports: any;
}

declare module 'react-router-drilldown/src/withTransitionContext' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-drilldown/lib/index.js' {
  declare module.exports: $Exports<'react-router-drilldown/lib/index'>;
}
declare module 'react-router-drilldown/lib/withTransitionContext.js' {
  declare module.exports: $Exports<'react-router-drilldown/lib/withTransitionContext'>;
}
declare module 'react-router-drilldown/src/index.js' {
  declare module.exports: $Exports<'react-router-drilldown/src/index'>;
}
declare module 'react-router-drilldown/src/withTransitionContext.js' {
  declare module.exports: $Exports<'react-router-drilldown/src/withTransitionContext'>;
}
