// flow-typed signature: 22c98fdc5c0f58c7f243b2ffe9c4a706
// flow-typed version: <<STUB>>/react-widgets_v^3.4.8/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-widgets'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-widgets' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-widgets/build/browser.config' {
  declare module.exports: any;
}

declare module 'react-widgets/build/configure-shim' {
  declare module.exports: any;
}

declare module 'react-widgets/build/dev.config' {
  declare module.exports: any;
}

declare module 'react-widgets/build/docs.config' {
  declare module.exports: any;
}

declare module 'react-widgets/build/lessToSass' {
  declare module.exports: any;
}

declare module 'react-widgets/build/localizers.config' {
  declare module.exports: any;
}

declare module 'react-widgets/build/make-config' {
  declare module.exports: any;
}

declare module 'react-widgets/build/test.config' {
  declare module.exports: any;
}

declare module 'react-widgets/dev/configure-globalize' {
  declare module.exports: any;
}

declare module 'react-widgets/dev/configure-moment' {
  declare module.exports: any;
}

declare module 'react-widgets/dev/configure-simplenumber' {
  declare module.exports: any;
}

declare module 'react-widgets/dev/dev' {
  declare module.exports: any;
}

declare module 'react-widgets/dist/react-widgets-globalize' {
  declare module.exports: any;
}

declare module 'react-widgets/dist/react-widgets-moment' {
  declare module.exports: any;
}

declare module 'react-widgets/dist/react-widgets-simple-number' {
  declare module.exports: any;
}

declare module 'react-widgets/dist/react-widgets' {
  declare module.exports: any;
}

declare module 'react-widgets/karma.conf-ci' {
  declare module.exports: any;
}

declare module 'react-widgets/karma.conf' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Button' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Calendar' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/CalendarView' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Century' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Combobox' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/ComboboxInput' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/configure' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/DateTimePicker' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/DateTimePickerInput' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Decade' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/DropdownList' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/DropdownListInput' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Footer' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Header' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/index' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Input' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/List' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Listbox' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/ListGroupable' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/ListOption' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/localizers/globalize' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/localizers/moment' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/localizers/simple-number' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/mixins/AriaDescendantMixin' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/mixins/AutoFocusMixin' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/mixins/DataFilterMixin' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/mixins/DataHelpersMixin' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/mixins/FocusMixin' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/mixins/ListMovementMixin' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/mixins/PopupScrollToMixin' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/mixins/PureRenderMixin' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/mixins/RtlChildContextMixin' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/mixins/RtlParentContextMixin' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/mixins/TimeoutMixin' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Month' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Multiselect' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/MultiselectInput' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/MultiselectTagList' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/NumberInput' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/NumberPicker' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Popup' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/ReplaceTransitionGroup' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Select' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/SelectList' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/SlideTransition' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/TimeList' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/_' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/caret' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/compat' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/configuration' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/constants' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/dataHelpers' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/dates' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/dom/animate' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/dom/support' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/filter' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/interaction' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/localizers' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/propTypes' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/repeater' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/validateListInterface' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/widgetHelpers' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Widget' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Year' {
  declare module.exports: any;
}

declare module 'react-widgets/vendor/es5-sham.min' {
  declare module.exports: any;
}

declare module 'react-widgets/vendor/es5-shim.min' {
  declare module.exports: any;
}

declare module 'react-widgets/vendor/html5shiv.min' {
  declare module.exports: any;
}

declare module 'react-widgets/vendor/jquery-1.11.2.min' {
  declare module.exports: any;
}

declare module 'react-widgets/vendor/phantomjs-shim' {
  declare module.exports: any;
}

declare module 'react-widgets/vendor/sinon-1.10.3' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-widgets/build/browser.config.js' {
  declare module.exports: $Exports<'react-widgets/build/browser.config'>;
}
declare module 'react-widgets/build/configure-shim.js' {
  declare module.exports: $Exports<'react-widgets/build/configure-shim'>;
}
declare module 'react-widgets/build/dev.config.js' {
  declare module.exports: $Exports<'react-widgets/build/dev.config'>;
}
declare module 'react-widgets/build/docs.config.js' {
  declare module.exports: $Exports<'react-widgets/build/docs.config'>;
}
declare module 'react-widgets/build/lessToSass.js' {
  declare module.exports: $Exports<'react-widgets/build/lessToSass'>;
}
declare module 'react-widgets/build/localizers.config.js' {
  declare module.exports: $Exports<'react-widgets/build/localizers.config'>;
}
declare module 'react-widgets/build/make-config.js' {
  declare module.exports: $Exports<'react-widgets/build/make-config'>;
}
declare module 'react-widgets/build/test.config.js' {
  declare module.exports: $Exports<'react-widgets/build/test.config'>;
}
declare module 'react-widgets/dev/configure-globalize.js' {
  declare module.exports: $Exports<'react-widgets/dev/configure-globalize'>;
}
declare module 'react-widgets/dev/configure-moment.js' {
  declare module.exports: $Exports<'react-widgets/dev/configure-moment'>;
}
declare module 'react-widgets/dev/configure-simplenumber.js' {
  declare module.exports: $Exports<'react-widgets/dev/configure-simplenumber'>;
}
declare module 'react-widgets/dev/dev.jsx' {
  declare module.exports: $Exports<'react-widgets/dev/dev'>;
}
declare module 'react-widgets/dist/react-widgets-globalize.js' {
  declare module.exports: $Exports<'react-widgets/dist/react-widgets-globalize'>;
}
declare module 'react-widgets/dist/react-widgets-moment.js' {
  declare module.exports: $Exports<'react-widgets/dist/react-widgets-moment'>;
}
declare module 'react-widgets/dist/react-widgets-simple-number.js' {
  declare module.exports: $Exports<'react-widgets/dist/react-widgets-simple-number'>;
}
declare module 'react-widgets/dist/react-widgets.js' {
  declare module.exports: $Exports<'react-widgets/dist/react-widgets'>;
}
declare module 'react-widgets/karma.conf-ci.js' {
  declare module.exports: $Exports<'react-widgets/karma.conf-ci'>;
}
declare module 'react-widgets/karma.conf.js' {
  declare module.exports: $Exports<'react-widgets/karma.conf'>;
}
declare module 'react-widgets/lib/Button.js' {
  declare module.exports: $Exports<'react-widgets/lib/Button'>;
}
declare module 'react-widgets/lib/Calendar.js' {
  declare module.exports: $Exports<'react-widgets/lib/Calendar'>;
}
declare module 'react-widgets/lib/CalendarView.js' {
  declare module.exports: $Exports<'react-widgets/lib/CalendarView'>;
}
declare module 'react-widgets/lib/Century.js' {
  declare module.exports: $Exports<'react-widgets/lib/Century'>;
}
declare module 'react-widgets/lib/Combobox.js' {
  declare module.exports: $Exports<'react-widgets/lib/Combobox'>;
}
declare module 'react-widgets/lib/ComboboxInput.js' {
  declare module.exports: $Exports<'react-widgets/lib/ComboboxInput'>;
}
declare module 'react-widgets/lib/configure.js' {
  declare module.exports: $Exports<'react-widgets/lib/configure'>;
}
declare module 'react-widgets/lib/DateTimePicker.js' {
  declare module.exports: $Exports<'react-widgets/lib/DateTimePicker'>;
}
declare module 'react-widgets/lib/DateTimePickerInput.js' {
  declare module.exports: $Exports<'react-widgets/lib/DateTimePickerInput'>;
}
declare module 'react-widgets/lib/Decade.js' {
  declare module.exports: $Exports<'react-widgets/lib/Decade'>;
}
declare module 'react-widgets/lib/DropdownList.js' {
  declare module.exports: $Exports<'react-widgets/lib/DropdownList'>;
}
declare module 'react-widgets/lib/DropdownListInput.js' {
  declare module.exports: $Exports<'react-widgets/lib/DropdownListInput'>;
}
declare module 'react-widgets/lib/Footer.js' {
  declare module.exports: $Exports<'react-widgets/lib/Footer'>;
}
declare module 'react-widgets/lib/Header.js' {
  declare module.exports: $Exports<'react-widgets/lib/Header'>;
}
declare module 'react-widgets/lib/index.js' {
  declare module.exports: $Exports<'react-widgets/lib/index'>;
}
declare module 'react-widgets/lib/Input.js' {
  declare module.exports: $Exports<'react-widgets/lib/Input'>;
}
declare module 'react-widgets/lib/List.js' {
  declare module.exports: $Exports<'react-widgets/lib/List'>;
}
declare module 'react-widgets/lib/Listbox.js' {
  declare module.exports: $Exports<'react-widgets/lib/Listbox'>;
}
declare module 'react-widgets/lib/ListGroupable.js' {
  declare module.exports: $Exports<'react-widgets/lib/ListGroupable'>;
}
declare module 'react-widgets/lib/ListOption.js' {
  declare module.exports: $Exports<'react-widgets/lib/ListOption'>;
}
declare module 'react-widgets/lib/localizers/globalize.js' {
  declare module.exports: $Exports<'react-widgets/lib/localizers/globalize'>;
}
declare module 'react-widgets/lib/localizers/moment.js' {
  declare module.exports: $Exports<'react-widgets/lib/localizers/moment'>;
}
declare module 'react-widgets/lib/localizers/simple-number.js' {
  declare module.exports: $Exports<'react-widgets/lib/localizers/simple-number'>;
}
declare module 'react-widgets/lib/mixins/AriaDescendantMixin.js' {
  declare module.exports: $Exports<'react-widgets/lib/mixins/AriaDescendantMixin'>;
}
declare module 'react-widgets/lib/mixins/AutoFocusMixin.js' {
  declare module.exports: $Exports<'react-widgets/lib/mixins/AutoFocusMixin'>;
}
declare module 'react-widgets/lib/mixins/DataFilterMixin.js' {
  declare module.exports: $Exports<'react-widgets/lib/mixins/DataFilterMixin'>;
}
declare module 'react-widgets/lib/mixins/DataHelpersMixin.js' {
  declare module.exports: $Exports<'react-widgets/lib/mixins/DataHelpersMixin'>;
}
declare module 'react-widgets/lib/mixins/FocusMixin.js' {
  declare module.exports: $Exports<'react-widgets/lib/mixins/FocusMixin'>;
}
declare module 'react-widgets/lib/mixins/ListMovementMixin.js' {
  declare module.exports: $Exports<'react-widgets/lib/mixins/ListMovementMixin'>;
}
declare module 'react-widgets/lib/mixins/PopupScrollToMixin.js' {
  declare module.exports: $Exports<'react-widgets/lib/mixins/PopupScrollToMixin'>;
}
declare module 'react-widgets/lib/mixins/PureRenderMixin.js' {
  declare module.exports: $Exports<'react-widgets/lib/mixins/PureRenderMixin'>;
}
declare module 'react-widgets/lib/mixins/RtlChildContextMixin.js' {
  declare module.exports: $Exports<'react-widgets/lib/mixins/RtlChildContextMixin'>;
}
declare module 'react-widgets/lib/mixins/RtlParentContextMixin.js' {
  declare module.exports: $Exports<'react-widgets/lib/mixins/RtlParentContextMixin'>;
}
declare module 'react-widgets/lib/mixins/TimeoutMixin.js' {
  declare module.exports: $Exports<'react-widgets/lib/mixins/TimeoutMixin'>;
}
declare module 'react-widgets/lib/Month.js' {
  declare module.exports: $Exports<'react-widgets/lib/Month'>;
}
declare module 'react-widgets/lib/Multiselect.js' {
  declare module.exports: $Exports<'react-widgets/lib/Multiselect'>;
}
declare module 'react-widgets/lib/MultiselectInput.js' {
  declare module.exports: $Exports<'react-widgets/lib/MultiselectInput'>;
}
declare module 'react-widgets/lib/MultiselectTagList.js' {
  declare module.exports: $Exports<'react-widgets/lib/MultiselectTagList'>;
}
declare module 'react-widgets/lib/NumberInput.js' {
  declare module.exports: $Exports<'react-widgets/lib/NumberInput'>;
}
declare module 'react-widgets/lib/NumberPicker.js' {
  declare module.exports: $Exports<'react-widgets/lib/NumberPicker'>;
}
declare module 'react-widgets/lib/Popup.js' {
  declare module.exports: $Exports<'react-widgets/lib/Popup'>;
}
declare module 'react-widgets/lib/ReplaceTransitionGroup.js' {
  declare module.exports: $Exports<'react-widgets/lib/ReplaceTransitionGroup'>;
}
declare module 'react-widgets/lib/Select.js' {
  declare module.exports: $Exports<'react-widgets/lib/Select'>;
}
declare module 'react-widgets/lib/SelectList.js' {
  declare module.exports: $Exports<'react-widgets/lib/SelectList'>;
}
declare module 'react-widgets/lib/SlideTransition.js' {
  declare module.exports: $Exports<'react-widgets/lib/SlideTransition'>;
}
declare module 'react-widgets/lib/TimeList.js' {
  declare module.exports: $Exports<'react-widgets/lib/TimeList'>;
}
declare module 'react-widgets/lib/util/_.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/_'>;
}
declare module 'react-widgets/lib/util/caret.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/caret'>;
}
declare module 'react-widgets/lib/util/compat.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/compat'>;
}
declare module 'react-widgets/lib/util/configuration.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/configuration'>;
}
declare module 'react-widgets/lib/util/constants.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/constants'>;
}
declare module 'react-widgets/lib/util/dataHelpers.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/dataHelpers'>;
}
declare module 'react-widgets/lib/util/dates.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/dates'>;
}
declare module 'react-widgets/lib/util/dom/animate.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/dom/animate'>;
}
declare module 'react-widgets/lib/util/dom/support.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/dom/support'>;
}
declare module 'react-widgets/lib/util/filter.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/filter'>;
}
declare module 'react-widgets/lib/util/interaction.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/interaction'>;
}
declare module 'react-widgets/lib/util/localizers.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/localizers'>;
}
declare module 'react-widgets/lib/util/propTypes.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/propTypes'>;
}
declare module 'react-widgets/lib/util/repeater.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/repeater'>;
}
declare module 'react-widgets/lib/util/validateListInterface.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/validateListInterface'>;
}
declare module 'react-widgets/lib/util/widgetHelpers.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/widgetHelpers'>;
}
declare module 'react-widgets/lib/Widget.js' {
  declare module.exports: $Exports<'react-widgets/lib/Widget'>;
}
declare module 'react-widgets/lib/Year.js' {
  declare module.exports: $Exports<'react-widgets/lib/Year'>;
}
declare module 'react-widgets/vendor/es5-sham.min.js' {
  declare module.exports: $Exports<'react-widgets/vendor/es5-sham.min'>;
}
declare module 'react-widgets/vendor/es5-shim.min.js' {
  declare module.exports: $Exports<'react-widgets/vendor/es5-shim.min'>;
}
declare module 'react-widgets/vendor/html5shiv.min.js' {
  declare module.exports: $Exports<'react-widgets/vendor/html5shiv.min'>;
}
declare module 'react-widgets/vendor/jquery-1.11.2.min.js' {
  declare module.exports: $Exports<'react-widgets/vendor/jquery-1.11.2.min'>;
}
declare module 'react-widgets/vendor/phantomjs-shim.js' {
  declare module.exports: $Exports<'react-widgets/vendor/phantomjs-shim'>;
}
declare module 'react-widgets/vendor/sinon-1.10.3.js' {
  declare module.exports: $Exports<'react-widgets/vendor/sinon-1.10.3'>;
}
