// flow-typed signature: f501b503f17a7ed8539c0da6e067486a
// flow-typed version: <<STUB>>/redux-features-hot-loader_v^1.0.3/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-features-hot-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-features-hot-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-features-hot-loader/flow-typed/npm/@jedwards1211/eslint-config_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/@jedwards1211/eslint-config-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/babel-plugin-istanbul_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/babel-polyfill_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/babel-preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/babel-preset-stage-1_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/babel-register_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/babel-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/chai_v4.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/copy_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/coveralls_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/es6-promisify_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/eslint-watch_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/flow-watch_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/istanbul_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/json-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/loader-utils_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/lodash.map_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/mocha_v3.1.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/nyc_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/phantomjs-prebuilt_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/redux_v3.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/rimraf_v2.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/semantic-release_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/validate-commit-msg_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/wdio-mocha-framework_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/wdio-phantomjs-service_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/wdio-spec-reporter_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/webdriverio_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/flow-typed/npm/webpack-dev-server_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/lib/index' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/src/index' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/wdio.conf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-features-hot-loader/flow-typed/npm/@jedwards1211/eslint-config_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/@jedwards1211/eslint-config_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/@jedwards1211/eslint-config-flow_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/@jedwards1211/eslint-config-flow_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/babel-plugin-istanbul_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/babel-plugin-istanbul_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/babel-polyfill_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/babel-polyfill_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/babel-preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/babel-preset-flow_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/babel-preset-stage-1_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/babel-preset-stage-1_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/babel-register_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/babel-register_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/babel-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/babel-runtime_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/chai_v4.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/chai_v4.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/copy_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/copy_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/coveralls_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/coveralls_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/es6-promisify_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/es6-promisify_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/eslint-watch_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/eslint-watch_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/flow-watch_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/flow-watch_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/husky_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/istanbul_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/istanbul_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/json-loader_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/json-loader_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/loader-utils_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/loader-utils_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/lodash.map_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/lodash.map_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/mocha_v3.1.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/mocha_v3.1.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/nyc_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/nyc_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/phantomjs-prebuilt_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/phantomjs-prebuilt_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/redux_v3.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/redux_v3.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/rimraf_v2.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/rimraf_v2.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/semantic-release_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/semantic-release_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/validate-commit-msg_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/validate-commit-msg_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/wdio-mocha-framework_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/wdio-mocha-framework_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/wdio-phantomjs-service_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/wdio-phantomjs-service_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/wdio-spec-reporter_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/wdio-spec-reporter_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/webdriverio_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/webdriverio_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/webpack_vx.x.x'>;
}
declare module 'redux-features-hot-loader/flow-typed/npm/webpack-dev-server_vx.x.x.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/flow-typed/npm/webpack-dev-server_vx.x.x'>;
}
declare module 'redux-features-hot-loader/lib/index.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/lib/index'>;
}
declare module 'redux-features-hot-loader/src/index.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/src/index'>;
}
declare module 'redux-features-hot-loader/wdio.conf.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/wdio.conf'>;
}
