// flow-typed signature: e8f29a10e52383502412f46644865e2b
// flow-typed version: <<STUB>>/redux-immutable-collections_v^2.2.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-immutable-collections'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-immutable-collections' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-immutable-collections/lib/createReducer' {
  declare module.exports: any;
}

declare module 'redux-immutable-collections/lib/keyedCollection' {
  declare module.exports: any;
}

declare module 'redux-immutable-collections/src/createReducer' {
  declare module.exports: any;
}

declare module 'redux-immutable-collections/src/keyedCollection' {
  declare module.exports: any;
}

declare module 'redux-immutable-collections/temp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-immutable-collections/lib/createReducer.js' {
  declare module.exports: $Exports<'redux-immutable-collections/lib/createReducer'>;
}
declare module 'redux-immutable-collections/lib/keyedCollection.js' {
  declare module.exports: $Exports<'redux-immutable-collections/lib/keyedCollection'>;
}
declare module 'redux-immutable-collections/src/createReducer.js' {
  declare module.exports: $Exports<'redux-immutable-collections/src/createReducer'>;
}
declare module 'redux-immutable-collections/src/keyedCollection.js' {
  declare module.exports: $Exports<'redux-immutable-collections/src/keyedCollection'>;
}
declare module 'redux-immutable-collections/temp.js' {
  declare module.exports: $Exports<'redux-immutable-collections/temp'>;
}
