// flow-typed signature: e96657c487ee2870fda0f47687e66464
// flow-typed version: <<STUB>>/redux-features-hot-loader_v^1.0.2/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-features-hot-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-features-hot-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-features-hot-loader/lib/index' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/src/index' {
  declare module.exports: any;
}

declare module 'redux-features-hot-loader/wdio.conf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-features-hot-loader/lib/index.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/lib/index'>;
}
declare module 'redux-features-hot-loader/src/index.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/src/index'>;
}
declare module 'redux-features-hot-loader/wdio.conf.js' {
  declare module.exports: $Exports<'redux-features-hot-loader/wdio.conf'>;
}
