// flow-typed signature: 637847f626633bb2ba60c0b0bfde54d9
// flow-typed version: <<STUB>>/replify_v^1.2.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'replify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'replify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'replify/examples/http-client' {
  declare module.exports: any;
}

declare module 'replify/examples/replpad' {
  declare module.exports: any;
}

declare module 'replify/examples/simple' {
  declare module.exports: any;
}

declare module 'replify/replify' {
  declare module.exports: any;
}

declare module 'replify/test/replify.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'replify/examples/http-client.js' {
  declare module.exports: $Exports<'replify/examples/http-client'>;
}
declare module 'replify/examples/replpad.js' {
  declare module.exports: $Exports<'replify/examples/replpad'>;
}
declare module 'replify/examples/simple.js' {
  declare module.exports: $Exports<'replify/examples/simple'>;
}
declare module 'replify/replify.js' {
  declare module.exports: $Exports<'replify/replify'>;
}
declare module 'replify/test/replify.test.js' {
  declare module.exports: $Exports<'replify/test/replify.test'>;
}
