// flow-typed signature: eec70437fd8b7f308e72dd7877c0d037
// flow-typed version: <<STUB>>/repl-client_v^0.3.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'repl-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'repl-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'repl-client/examples/simple-http/simple-http' {
  declare module.exports: any;
}

declare module 'repl-client/examples/socket.io-ann/data' {
  declare module.exports: any;
}

declare module 'repl-client/examples/socket.io-ann/mix' {
  declare module.exports: any;
}

declare module 'repl-client/examples/socket.io-ann/rc.io' {
  declare module.exports: any;
}

declare module 'repl-client/examples/socket.io/client' {
  declare module.exports: any;
}

declare module 'repl-client/examples/socket.io/io' {
  declare module.exports: any;
}

declare module 'repl-client/examples/socket.io/mix' {
  declare module.exports: any;
}

declare module 'repl-client/repl-client' {
  declare module.exports: any;
}

// Filename aliases
declare module 'repl-client/examples/simple-http/simple-http.js' {
  declare module.exports: $Exports<'repl-client/examples/simple-http/simple-http'>;
}
declare module 'repl-client/examples/socket.io-ann/data.js' {
  declare module.exports: $Exports<'repl-client/examples/socket.io-ann/data'>;
}
declare module 'repl-client/examples/socket.io-ann/mix.js' {
  declare module.exports: $Exports<'repl-client/examples/socket.io-ann/mix'>;
}
declare module 'repl-client/examples/socket.io-ann/rc.io.js' {
  declare module.exports: $Exports<'repl-client/examples/socket.io-ann/rc.io'>;
}
declare module 'repl-client/examples/socket.io/client.js' {
  declare module.exports: $Exports<'repl-client/examples/socket.io/client'>;
}
declare module 'repl-client/examples/socket.io/io.js' {
  declare module.exports: $Exports<'repl-client/examples/socket.io/io'>;
}
declare module 'repl-client/examples/socket.io/mix.js' {
  declare module.exports: $Exports<'repl-client/examples/socket.io/mix'>;
}
declare module 'repl-client/repl-client.js' {
  declare module.exports: $Exports<'repl-client/repl-client'>;
}
