// flow-typed signature: f42d9edb5318865eba6bd0184e049c6c
// flow-typed version: <<STUB>>/superagent-logger_v^1.1.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'superagent-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'superagent-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'superagent-logger/example-options' {
  declare module.exports: any;
}

declare module 'superagent-logger/example' {
  declare module.exports: any;
}

declare module 'superagent-logger/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'superagent-logger/example-options.js' {
  declare module.exports: $Exports<'superagent-logger/example-options'>;
}
declare module 'superagent-logger/example.js' {
  declare module.exports: $Exports<'superagent-logger/example'>;
}
declare module 'superagent-logger/lib/index.js' {
  declare module.exports: $Exports<'superagent-logger/lib/index'>;
}
