// flow-typed signature: 81ad29aecfced614af6c86d43b2226bf
// flow-typed version: <<STUB>>/superagent-use_v^0.1.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'superagent-use'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'superagent-use' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'superagent-use/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'superagent-use/index' {
  declare module.exports: $Exports<'superagent-use'>;
}
declare module 'superagent-use/index.js' {
  declare module.exports: $Exports<'superagent-use'>;
}
declare module 'superagent-use/test/index.js' {
  declare module.exports: $Exports<'superagent-use/test/index'>;
}
