// flow-typed signature: ae7dd823ddc611f4334e74b2b950a67c
// flow-typed version: <<STUB>>/superagent-verbose-errors_v^1.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'superagent-verbose-errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'superagent-verbose-errors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'superagent-verbose-errors/index' {
  declare module.exports: $Exports<'superagent-verbose-errors'>;
}
declare module 'superagent-verbose-errors/index.js' {
  declare module.exports: $Exports<'superagent-verbose-errors'>;
}
