// flow-typed signature: 33e45e9b6465c9fc500e7a1d8b36a4a9
// flow-typed version: <<STUB>>/superagent-prefix_v^0.0.2/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'superagent-prefix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'superagent-prefix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'superagent-prefix/index' {
  declare module.exports: $Exports<'superagent-prefix'>;
}
declare module 'superagent-prefix/index.js' {
  declare module.exports: $Exports<'superagent-prefix'>;
}
