// flow-typed signature: cd3a852d9fb1637eba1b3de25beb2cba
// flow-typed version: <<STUB>>/touch_v^3.1.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'touch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'touch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'touch/bin/nodetouch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'touch/bin/nodetouch.js' {
  declare module.exports: $Exports<'touch/bin/nodetouch'>;
}
declare module 'touch/index' {
  declare module.exports: $Exports<'touch'>;
}
declare module 'touch/index.js' {
  declare module.exports: $Exports<'touch'>;
}
