// flow-typed signature: 3ff5ca72c99611fc1fbcdd7bdc9cec5a
// flow-typed version: <<STUB>>/umzug_v^1.11.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'umzug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'umzug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'umzug/gulpfile' {
  declare module.exports: any;
}

declare module 'umzug/lib/helper' {
  declare module.exports: any;
}

declare module 'umzug/lib/migration' {
  declare module.exports: any;
}

declare module 'umzug/lib/storages/json' {
  declare module.exports: any;
}

declare module 'umzug/lib/storages/none' {
  declare module.exports: any;
}

declare module 'umzug/lib/storages/sequelize' {
  declare module.exports: any;
}

declare module 'umzug/test/helper' {
  declare module.exports: any;
}

declare module 'umzug/test/index/constructor.test' {
  declare module.exports: any;
}

declare module 'umzug/test/index/down.test' {
  declare module.exports: any;
}

declare module 'umzug/test/index/execute.test' {
  declare module.exports: any;
}

declare module 'umzug/test/index/executed.test' {
  declare module.exports: any;
}

declare module 'umzug/test/index/index' {
  declare module.exports: any;
}

declare module 'umzug/test/index/pending.test' {
  declare module.exports: any;
}

declare module 'umzug/test/index/up.test' {
  declare module.exports: any;
}

declare module 'umzug/test/storages/index' {
  declare module.exports: any;
}

declare module 'umzug/test/storages/json.test' {
  declare module.exports: any;
}

declare module 'umzug/test/storages/none.test' {
  declare module.exports: any;
}

declare module 'umzug/test/storages/sequelize.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'umzug/gulpfile.js' {
  declare module.exports: $Exports<'umzug/gulpfile'>;
}
declare module 'umzug/index' {
  declare module.exports: $Exports<'umzug'>;
}
declare module 'umzug/index.js' {
  declare module.exports: $Exports<'umzug'>;
}
declare module 'umzug/lib/helper.js' {
  declare module.exports: $Exports<'umzug/lib/helper'>;
}
declare module 'umzug/lib/migration.js' {
  declare module.exports: $Exports<'umzug/lib/migration'>;
}
declare module 'umzug/lib/storages/json.js' {
  declare module.exports: $Exports<'umzug/lib/storages/json'>;
}
declare module 'umzug/lib/storages/none.js' {
  declare module.exports: $Exports<'umzug/lib/storages/none'>;
}
declare module 'umzug/lib/storages/sequelize.js' {
  declare module.exports: $Exports<'umzug/lib/storages/sequelize'>;
}
declare module 'umzug/test/helper.js' {
  declare module.exports: $Exports<'umzug/test/helper'>;
}
declare module 'umzug/test/index/constructor.test.js' {
  declare module.exports: $Exports<'umzug/test/index/constructor.test'>;
}
declare module 'umzug/test/index/down.test.js' {
  declare module.exports: $Exports<'umzug/test/index/down.test'>;
}
declare module 'umzug/test/index/execute.test.js' {
  declare module.exports: $Exports<'umzug/test/index/execute.test'>;
}
declare module 'umzug/test/index/executed.test.js' {
  declare module.exports: $Exports<'umzug/test/index/executed.test'>;
}
declare module 'umzug/test/index/index.js' {
  declare module.exports: $Exports<'umzug/test/index/index'>;
}
declare module 'umzug/test/index/pending.test.js' {
  declare module.exports: $Exports<'umzug/test/index/pending.test'>;
}
declare module 'umzug/test/index/up.test.js' {
  declare module.exports: $Exports<'umzug/test/index/up.test'>;
}
declare module 'umzug/test/storages/index.js' {
  declare module.exports: $Exports<'umzug/test/storages/index'>;
}
declare module 'umzug/test/storages/json.test.js' {
  declare module.exports: $Exports<'umzug/test/storages/json.test'>;
}
declare module 'umzug/test/storages/none.test.js' {
  declare module.exports: $Exports<'umzug/test/storages/none.test'>;
}
declare module 'umzug/test/storages/sequelize.test.js' {
  declare module.exports: $Exports<'umzug/test/storages/sequelize.test'>;
}
