// flow-typed signature: b4e31dfaba4626de38c11be85fbe3d28
// flow-typed version: <<STUB>>/umzug_v^2.1.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'umzug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'umzug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'umzug/gulpfile' {
  declare module.exports: any;
}

declare module 'umzug/lib/helper' {
  declare module.exports: any;
}

declare module 'umzug/lib/index' {
  declare module.exports: any;
}

declare module 'umzug/lib/migration' {
  declare module.exports: any;
}

declare module 'umzug/lib/storages/json' {
  declare module.exports: any;
}

declare module 'umzug/lib/storages/JSONStorage' {
  declare module.exports: any;
}

declare module 'umzug/lib/storages/MongoDBStorage' {
  declare module.exports: any;
}

declare module 'umzug/lib/storages/none' {
  declare module.exports: any;
}

declare module 'umzug/lib/storages/sequelize' {
  declare module.exports: any;
}

declare module 'umzug/lib/storages/SequelizeStorage' {
  declare module.exports: any;
}

declare module 'umzug/lib/storages/Storage' {
  declare module.exports: any;
}

declare module 'umzug/src/helper' {
  declare module.exports: any;
}

declare module 'umzug/src/index' {
  declare module.exports: any;
}

declare module 'umzug/src/migration' {
  declare module.exports: any;
}

declare module 'umzug/src/storages/json' {
  declare module.exports: any;
}

declare module 'umzug/src/storages/JSONStorage' {
  declare module.exports: any;
}

declare module 'umzug/src/storages/MongoDBStorage' {
  declare module.exports: any;
}

declare module 'umzug/src/storages/none' {
  declare module.exports: any;
}

declare module 'umzug/src/storages/sequelize' {
  declare module.exports: any;
}

declare module 'umzug/src/storages/SequelizeStorage' {
  declare module.exports: any;
}

declare module 'umzug/src/storages/Storage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'umzug/gulpfile.js' {
  declare module.exports: $Exports<'umzug/gulpfile'>;
}
declare module 'umzug/lib/helper.js' {
  declare module.exports: $Exports<'umzug/lib/helper'>;
}
declare module 'umzug/lib/index.js' {
  declare module.exports: $Exports<'umzug/lib/index'>;
}
declare module 'umzug/lib/migration.js' {
  declare module.exports: $Exports<'umzug/lib/migration'>;
}
declare module 'umzug/lib/storages/json.js' {
  declare module.exports: $Exports<'umzug/lib/storages/json'>;
}
declare module 'umzug/lib/storages/JSONStorage.js' {
  declare module.exports: $Exports<'umzug/lib/storages/JSONStorage'>;
}
declare module 'umzug/lib/storages/MongoDBStorage.js' {
  declare module.exports: $Exports<'umzug/lib/storages/MongoDBStorage'>;
}
declare module 'umzug/lib/storages/none.js' {
  declare module.exports: $Exports<'umzug/lib/storages/none'>;
}
declare module 'umzug/lib/storages/sequelize.js' {
  declare module.exports: $Exports<'umzug/lib/storages/sequelize'>;
}
declare module 'umzug/lib/storages/SequelizeStorage.js' {
  declare module.exports: $Exports<'umzug/lib/storages/SequelizeStorage'>;
}
declare module 'umzug/lib/storages/Storage.js' {
  declare module.exports: $Exports<'umzug/lib/storages/Storage'>;
}
declare module 'umzug/src/helper.js' {
  declare module.exports: $Exports<'umzug/src/helper'>;
}
declare module 'umzug/src/index.js' {
  declare module.exports: $Exports<'umzug/src/index'>;
}
declare module 'umzug/src/migration.js' {
  declare module.exports: $Exports<'umzug/src/migration'>;
}
declare module 'umzug/src/storages/json.js' {
  declare module.exports: $Exports<'umzug/src/storages/json'>;
}
declare module 'umzug/src/storages/JSONStorage.js' {
  declare module.exports: $Exports<'umzug/src/storages/JSONStorage'>;
}
declare module 'umzug/src/storages/MongoDBStorage.js' {
  declare module.exports: $Exports<'umzug/src/storages/MongoDBStorage'>;
}
declare module 'umzug/src/storages/none.js' {
  declare module.exports: $Exports<'umzug/src/storages/none'>;
}
declare module 'umzug/src/storages/sequelize.js' {
  declare module.exports: $Exports<'umzug/src/storages/sequelize'>;
}
declare module 'umzug/src/storages/SequelizeStorage.js' {
  declare module.exports: $Exports<'umzug/src/storages/SequelizeStorage'>;
}
declare module 'umzug/src/storages/Storage.js' {
  declare module.exports: $Exports<'umzug/src/storages/Storage'>;
}
