# Usage: cd scripts/dev-dbs && docker-compose up
# Note: this is a version 1 file so that it works in Solano, which has docker-compose 1.5.2
mysql:
  image: mysql:5.6
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=password
redis:
  image: redis:3.2
  ports:
    - 6379:6379
dynamodb:
  build: .
  dockerfile: Dockerfile-DynamoLocal
  ports:
    - 8000:8000
