// flow-typed signature: 2bdea678600ff0c8b76af74c600aa07f
// flow-typed version: <<STUB>>/@jcoreio/gauges_v^2.0.2/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jcoreio/gauges'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jcoreio/gauges' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@jcoreio/gauges/lib/AnimatedArcFill' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/lib/animateGauge' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/lib/ArcAlarmLegend' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/lib/ArcFill' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/lib/ArcGauge' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/lib/arcGaugeStyles' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/lib/gaugeStyles' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/lib/util/arcPath' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/lib/util/colors' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/lib/util/createTextMeasurer' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/lib/util/dummyRenderingContext' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/lib/util/FontMetricsCache' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/lib/util/layoutSvgText' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/lib/util/measureTextPolyfill' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/lib/util/pickFontSize' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/src/AnimatedArcFill' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/src/animateGauge' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/src/ArcAlarmLegend' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/src/ArcFill' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/src/ArcGauge' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/src/arcGaugeStyles' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/src/gaugeStyles' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/src/util/arcPath' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/src/util/colors' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/src/util/createTextMeasurer' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/src/util/dummyRenderingContext' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/src/util/FontMetricsCache' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/src/util/layoutSvgText' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/src/util/measureTextPolyfill' {
  declare module.exports: any;
}

declare module '@jcoreio/gauges/src/util/pickFontSize' {
  declare module.exports: any;
}

// Filename aliases
declare module '@jcoreio/gauges/lib/AnimatedArcFill.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/lib/AnimatedArcFill'>;
}
declare module '@jcoreio/gauges/lib/animateGauge.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/lib/animateGauge'>;
}
declare module '@jcoreio/gauges/lib/ArcAlarmLegend.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/lib/ArcAlarmLegend'>;
}
declare module '@jcoreio/gauges/lib/ArcFill.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/lib/ArcFill'>;
}
declare module '@jcoreio/gauges/lib/ArcGauge.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/lib/ArcGauge'>;
}
declare module '@jcoreio/gauges/lib/arcGaugeStyles.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/lib/arcGaugeStyles'>;
}
declare module '@jcoreio/gauges/lib/gaugeStyles.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/lib/gaugeStyles'>;
}
declare module '@jcoreio/gauges/lib/util/arcPath.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/lib/util/arcPath'>;
}
declare module '@jcoreio/gauges/lib/util/colors.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/lib/util/colors'>;
}
declare module '@jcoreio/gauges/lib/util/createTextMeasurer.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/lib/util/createTextMeasurer'>;
}
declare module '@jcoreio/gauges/lib/util/dummyRenderingContext.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/lib/util/dummyRenderingContext'>;
}
declare module '@jcoreio/gauges/lib/util/FontMetricsCache.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/lib/util/FontMetricsCache'>;
}
declare module '@jcoreio/gauges/lib/util/layoutSvgText.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/lib/util/layoutSvgText'>;
}
declare module '@jcoreio/gauges/lib/util/measureTextPolyfill.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/lib/util/measureTextPolyfill'>;
}
declare module '@jcoreio/gauges/lib/util/pickFontSize.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/lib/util/pickFontSize'>;
}
declare module '@jcoreio/gauges/src/AnimatedArcFill.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/src/AnimatedArcFill'>;
}
declare module '@jcoreio/gauges/src/animateGauge.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/src/animateGauge'>;
}
declare module '@jcoreio/gauges/src/ArcAlarmLegend.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/src/ArcAlarmLegend'>;
}
declare module '@jcoreio/gauges/src/ArcFill.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/src/ArcFill'>;
}
declare module '@jcoreio/gauges/src/ArcGauge.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/src/ArcGauge'>;
}
declare module '@jcoreio/gauges/src/arcGaugeStyles.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/src/arcGaugeStyles'>;
}
declare module '@jcoreio/gauges/src/gaugeStyles.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/src/gaugeStyles'>;
}
declare module '@jcoreio/gauges/src/util/arcPath.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/src/util/arcPath'>;
}
declare module '@jcoreio/gauges/src/util/colors.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/src/util/colors'>;
}
declare module '@jcoreio/gauges/src/util/createTextMeasurer.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/src/util/createTextMeasurer'>;
}
declare module '@jcoreio/gauges/src/util/dummyRenderingContext.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/src/util/dummyRenderingContext'>;
}
declare module '@jcoreio/gauges/src/util/FontMetricsCache.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/src/util/FontMetricsCache'>;
}
declare module '@jcoreio/gauges/src/util/layoutSvgText.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/src/util/layoutSvgText'>;
}
declare module '@jcoreio/gauges/src/util/measureTextPolyfill.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/src/util/measureTextPolyfill'>;
}
declare module '@jcoreio/gauges/src/util/pickFontSize.js' {
  declare module.exports: $Exports<'@jcoreio/gauges/src/util/pickFontSize'>;
}
