// flow-typed signature: 4793d17de092bc7d5fbcadf7fa061c81
// flow-typed version: <<STUB>>/@jcoreio/react-circular-progressbar_v^0.2.4/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jcoreio/react-circular-progressbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jcoreio/react-circular-progressbar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@jcoreio/react-circular-progressbar/build/index' {
  declare module.exports: any;
}

declare module '@jcoreio/react-circular-progressbar/docs/demo' {
  declare module.exports: any;
}

declare module '@jcoreio/react-circular-progressbar/docs/index' {
  declare module.exports: any;
}

declare module '@jcoreio/react-circular-progressbar/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@jcoreio/react-circular-progressbar/build/index.js' {
  declare module.exports: $Exports<'@jcoreio/react-circular-progressbar/build/index'>;
}
declare module '@jcoreio/react-circular-progressbar/docs/demo.jsx' {
  declare module.exports: $Exports<'@jcoreio/react-circular-progressbar/docs/demo'>;
}
declare module '@jcoreio/react-circular-progressbar/docs/index.js' {
  declare module.exports: $Exports<'@jcoreio/react-circular-progressbar/docs/index'>;
}
declare module '@jcoreio/react-circular-progressbar/webpack.config.js' {
  declare module.exports: $Exports<'@jcoreio/react-circular-progressbar/webpack.config'>;
}
