// flow-typed signature: 6ec4128ad68a85442d2ff051761cf8f5
// flow-typed version: <<STUB>>/@jcoreio/react-router-relative-links_v^1.0.2/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jcoreio/react-router-relative-links'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jcoreio/react-router-relative-links' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@jcoreio/react-router-relative-links/example/index' {
  declare module.exports: any;
}

declare module '@jcoreio/react-router-relative-links/lib/RelativeLinks' {
  declare module.exports: any;
}

declare module '@jcoreio/react-router-relative-links/lib/RelativeLinks.test' {
  declare module.exports: any;
}

declare module '@jcoreio/react-router-relative-links/modules/RelativeLinks' {
  declare module.exports: any;
}

declare module '@jcoreio/react-router-relative-links/modules/RelativeLinks.test' {
  declare module.exports: any;
}

declare module '@jcoreio/react-router-relative-links/umd/RelativeLinks' {
  declare module.exports: any;
}

declare module '@jcoreio/react-router-relative-links/umd/RelativeLinks.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@jcoreio/react-router-relative-links/example/index.js' {
  declare module.exports: $Exports<'@jcoreio/react-router-relative-links/example/index'>;
}
declare module '@jcoreio/react-router-relative-links/lib/RelativeLinks.js' {
  declare module.exports: $Exports<'@jcoreio/react-router-relative-links/lib/RelativeLinks'>;
}
declare module '@jcoreio/react-router-relative-links/lib/RelativeLinks.test.js' {
  declare module.exports: $Exports<'@jcoreio/react-router-relative-links/lib/RelativeLinks.test'>;
}
declare module '@jcoreio/react-router-relative-links/modules/RelativeLinks.js' {
  declare module.exports: $Exports<'@jcoreio/react-router-relative-links/modules/RelativeLinks'>;
}
declare module '@jcoreio/react-router-relative-links/modules/RelativeLinks.test.js' {
  declare module.exports: $Exports<'@jcoreio/react-router-relative-links/modules/RelativeLinks.test'>;
}
declare module '@jcoreio/react-router-relative-links/umd/RelativeLinks.js' {
  declare module.exports: $Exports<'@jcoreio/react-router-relative-links/umd/RelativeLinks'>;
}
declare module '@jcoreio/react-router-relative-links/umd/RelativeLinks.min.js' {
  declare module.exports: $Exports<'@jcoreio/react-router-relative-links/umd/RelativeLinks.min'>;
}
