// flow-typed signature: 6ba92a92a11dbe746808048c0edcc673
// flow-typed version: <<STUB>>/@jcoreio/react-router-apply-middleware_v^1.0.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jcoreio/react-router-apply-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jcoreio/react-router-apply-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@jcoreio/react-router-apply-middleware/example/index' {
  declare module.exports: any;
}

declare module '@jcoreio/react-router-apply-middleware/lib/applyMiddleware' {
  declare module.exports: any;
}

declare module '@jcoreio/react-router-apply-middleware/lib/applyMiddleware.test' {
  declare module.exports: any;
}

declare module '@jcoreio/react-router-apply-middleware/modules/applyMiddleware' {
  declare module.exports: any;
}

declare module '@jcoreio/react-router-apply-middleware/modules/applyMiddleware.test' {
  declare module.exports: any;
}

declare module '@jcoreio/react-router-apply-middleware/npm-scripts/postinstall' {
  declare module.exports: any;
}

declare module '@jcoreio/react-router-apply-middleware/umd/ReactRouterApplyMiddleware' {
  declare module.exports: any;
}

declare module '@jcoreio/react-router-apply-middleware/umd/ReactRouterApplyMiddleware.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@jcoreio/react-router-apply-middleware/example/index.js' {
  declare module.exports: $Exports<'@jcoreio/react-router-apply-middleware/example/index'>;
}
declare module '@jcoreio/react-router-apply-middleware/lib/applyMiddleware.js' {
  declare module.exports: $Exports<'@jcoreio/react-router-apply-middleware/lib/applyMiddleware'>;
}
declare module '@jcoreio/react-router-apply-middleware/lib/applyMiddleware.test.js' {
  declare module.exports: $Exports<'@jcoreio/react-router-apply-middleware/lib/applyMiddleware.test'>;
}
declare module '@jcoreio/react-router-apply-middleware/modules/applyMiddleware.js' {
  declare module.exports: $Exports<'@jcoreio/react-router-apply-middleware/modules/applyMiddleware'>;
}
declare module '@jcoreio/react-router-apply-middleware/modules/applyMiddleware.test.js' {
  declare module.exports: $Exports<'@jcoreio/react-router-apply-middleware/modules/applyMiddleware.test'>;
}
declare module '@jcoreio/react-router-apply-middleware/npm-scripts/postinstall.js' {
  declare module.exports: $Exports<'@jcoreio/react-router-apply-middleware/npm-scripts/postinstall'>;
}
declare module '@jcoreio/react-router-apply-middleware/umd/ReactRouterApplyMiddleware.js' {
  declare module.exports: $Exports<'@jcoreio/react-router-apply-middleware/umd/ReactRouterApplyMiddleware'>;
}
declare module '@jcoreio/react-router-apply-middleware/umd/ReactRouterApplyMiddleware.min.js' {
  declare module.exports: $Exports<'@jcoreio/react-router-apply-middleware/umd/ReactRouterApplyMiddleware.min'>;
}
