// flow-typed signature: 0f0971755f8731e22bf175db3be26d5f
// flow-typed version: <<STUB>>/@jcoreio/react-scrollable-table_v^1.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jcoreio/react-scrollable-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jcoreio/react-scrollable-table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@jcoreio/react-scrollable-table/lib/index' {
  declare module.exports: any;
}

declare module '@jcoreio/react-scrollable-table/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@jcoreio/react-scrollable-table/lib/index.js' {
  declare module.exports: $Exports<'@jcoreio/react-scrollable-table/lib/index'>;
}
declare module '@jcoreio/react-scrollable-table/src/index.js' {
  declare module.exports: $Exports<'@jcoreio/react-scrollable-table/src/index'>;
}
