// flow-typed signature: 7a5d63fd3b86334fd80c8d969a5631ca
// flow-typed version: <<STUB>>/@jcoreio/rubix_v^1.2.3/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jcoreio/rubix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jcoreio/rubix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@jcoreio/rubix/lib/Accordion' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Alert' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/AlertLink' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Badge' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/BNavDropdown' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/BPanel' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/BPanelGroup' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/BProgressBar' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Breadcrumb' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/BreadcrumbItem' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Button' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/ButtonGroup' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/ButtonToolbar' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Carousel' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Checkbox' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Clearfix' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Col' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Collapse' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/ControlLabel' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Dispatcher' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Dropdown' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/DropdownButton' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/DropdownHoverButton' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/DropdownMenu' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/DropdownToggle' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Fade' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Form' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/FormControl' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/FormControlFeedback' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/FormControlStatic' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/FormGroup' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Glyphicon' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Grid' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/HelpBlock' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Icon' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Image' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/index' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/InputGroup' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/isBrowser' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/isTouchDevice' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Jumbotron' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/L20n' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Label' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Lead' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/ListGroup' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/ListGroupItem' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/LoremIpsum' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Media' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/MediaBody' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/MediaHeading' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/MediaLeft' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/MediaList' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/MediaListItem' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/MediaRight' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/MenuItem' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Modal' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/ModalBody' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/ModalDialog' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/ModalFooter' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/ModalHeader' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/ModalTitle' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Nav' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Navbar' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/NavbarBrand' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/NavbarCollapse' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/NavbarHeader' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/NavbarToggle' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/NavDropdown' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/NavItem' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Overlay' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/OverlayTrigger' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/PageHeader' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/PageItem' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Pager' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Pagination' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Panel' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Popover' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Pricing' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Progress' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/ProgressBar' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/ProgressGroup' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Radio' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/ResponsiveEmbed' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Row' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/RSplitButton' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/SafeAnchor' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Sidebar' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/SplitButton' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/SplitHoverButton' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Tab' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/TabContainer' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/TabContent' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Table' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/TabPane' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Tabs' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Tag' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Thumbnail' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Timeline' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Tooltip' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/lib/Well' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Accordion' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Alert' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/AlertLink' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Badge' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/BNavDropdown' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/BPanel' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/BPanelGroup' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/BProgressBar' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Breadcrumb' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/BreadcrumbItem' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Button' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/ButtonGroup' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/ButtonToolbar' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Carousel' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Checkbox' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Clearfix' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Col' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Collapse' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/ControlLabel' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Dispatcher' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Dropdown' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/DropdownButton' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/DropdownHoverButton' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/DropdownMenu' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/DropdownToggle' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Fade' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Form' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/FormControl' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/FormControlFeedback' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/FormControlStatic' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/FormGroup' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Glyphicon' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Grid' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/HelpBlock' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Icon' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Image' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/index' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/InputGroup' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/isBrowser' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/isTouchDevice' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Jumbotron' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/L20n' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Label' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Lead' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/ListGroup' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/ListGroupItem' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/LoremIpsum' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Media' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/MediaBody' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/MediaHeading' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/MediaLeft' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/MediaList' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/MediaListItem' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/MediaRight' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/MenuItem' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Modal' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/ModalBody' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/ModalDialog' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/ModalFooter' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/ModalHeader' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/ModalTitle' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Nav' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Navbar' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/NavbarBrand' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/NavbarCollapse' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/NavbarHeader' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/NavbarToggle' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/NavDropdown' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/NavItem' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Overlay' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/OverlayTrigger' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/PageHeader' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/PageItem' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Pager' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Pagination' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Panel' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Popover' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Pricing' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Progress' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/ProgressBar' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/ProgressGroup' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Radio' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/ResponsiveEmbed' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Row' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/RSplitButton' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/SafeAnchor' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Sidebar' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/SplitButton' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/SplitHoverButton' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Tab' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/TabContainer' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/TabContent' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Table' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/TabPane' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Tabs' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Tag' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Thumbnail' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Timeline' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Tooltip' {
  declare module.exports: any;
}

declare module '@jcoreio/rubix/src/Well' {
  declare module.exports: any;
}

// Filename aliases
declare module '@jcoreio/rubix/lib/Accordion.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Accordion'>;
}
declare module '@jcoreio/rubix/lib/Alert.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Alert'>;
}
declare module '@jcoreio/rubix/lib/AlertLink.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/AlertLink'>;
}
declare module '@jcoreio/rubix/lib/Badge.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Badge'>;
}
declare module '@jcoreio/rubix/lib/BNavDropdown.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/BNavDropdown'>;
}
declare module '@jcoreio/rubix/lib/BPanel.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/BPanel'>;
}
declare module '@jcoreio/rubix/lib/BPanelGroup.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/BPanelGroup'>;
}
declare module '@jcoreio/rubix/lib/BProgressBar.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/BProgressBar'>;
}
declare module '@jcoreio/rubix/lib/Breadcrumb.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Breadcrumb'>;
}
declare module '@jcoreio/rubix/lib/BreadcrumbItem.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/BreadcrumbItem'>;
}
declare module '@jcoreio/rubix/lib/Button.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Button'>;
}
declare module '@jcoreio/rubix/lib/ButtonGroup.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/ButtonGroup'>;
}
declare module '@jcoreio/rubix/lib/ButtonToolbar.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/ButtonToolbar'>;
}
declare module '@jcoreio/rubix/lib/Carousel.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Carousel'>;
}
declare module '@jcoreio/rubix/lib/Checkbox.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Checkbox'>;
}
declare module '@jcoreio/rubix/lib/Clearfix.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Clearfix'>;
}
declare module '@jcoreio/rubix/lib/Col.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Col'>;
}
declare module '@jcoreio/rubix/lib/Collapse.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Collapse'>;
}
declare module '@jcoreio/rubix/lib/ControlLabel.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/ControlLabel'>;
}
declare module '@jcoreio/rubix/lib/Dispatcher.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Dispatcher'>;
}
declare module '@jcoreio/rubix/lib/Dropdown.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Dropdown'>;
}
declare module '@jcoreio/rubix/lib/DropdownButton.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/DropdownButton'>;
}
declare module '@jcoreio/rubix/lib/DropdownHoverButton.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/DropdownHoverButton'>;
}
declare module '@jcoreio/rubix/lib/DropdownMenu.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/DropdownMenu'>;
}
declare module '@jcoreio/rubix/lib/DropdownToggle.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/DropdownToggle'>;
}
declare module '@jcoreio/rubix/lib/Fade.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Fade'>;
}
declare module '@jcoreio/rubix/lib/Form.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Form'>;
}
declare module '@jcoreio/rubix/lib/FormControl.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/FormControl'>;
}
declare module '@jcoreio/rubix/lib/FormControlFeedback.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/FormControlFeedback'>;
}
declare module '@jcoreio/rubix/lib/FormControlStatic.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/FormControlStatic'>;
}
declare module '@jcoreio/rubix/lib/FormGroup.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/FormGroup'>;
}
declare module '@jcoreio/rubix/lib/Glyphicon.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Glyphicon'>;
}
declare module '@jcoreio/rubix/lib/Grid.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Grid'>;
}
declare module '@jcoreio/rubix/lib/HelpBlock.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/HelpBlock'>;
}
declare module '@jcoreio/rubix/lib/Icon.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Icon'>;
}
declare module '@jcoreio/rubix/lib/Image.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Image'>;
}
declare module '@jcoreio/rubix/lib/index.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/index'>;
}
declare module '@jcoreio/rubix/lib/InputGroup.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/InputGroup'>;
}
declare module '@jcoreio/rubix/lib/isBrowser.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/isBrowser'>;
}
declare module '@jcoreio/rubix/lib/isTouchDevice.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/isTouchDevice'>;
}
declare module '@jcoreio/rubix/lib/Jumbotron.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Jumbotron'>;
}
declare module '@jcoreio/rubix/lib/L20n.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/L20n'>;
}
declare module '@jcoreio/rubix/lib/Label.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Label'>;
}
declare module '@jcoreio/rubix/lib/Lead.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Lead'>;
}
declare module '@jcoreio/rubix/lib/ListGroup.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/ListGroup'>;
}
declare module '@jcoreio/rubix/lib/ListGroupItem.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/ListGroupItem'>;
}
declare module '@jcoreio/rubix/lib/LoremIpsum.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/LoremIpsum'>;
}
declare module '@jcoreio/rubix/lib/Media.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Media'>;
}
declare module '@jcoreio/rubix/lib/MediaBody.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/MediaBody'>;
}
declare module '@jcoreio/rubix/lib/MediaHeading.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/MediaHeading'>;
}
declare module '@jcoreio/rubix/lib/MediaLeft.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/MediaLeft'>;
}
declare module '@jcoreio/rubix/lib/MediaList.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/MediaList'>;
}
declare module '@jcoreio/rubix/lib/MediaListItem.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/MediaListItem'>;
}
declare module '@jcoreio/rubix/lib/MediaRight.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/MediaRight'>;
}
declare module '@jcoreio/rubix/lib/MenuItem.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/MenuItem'>;
}
declare module '@jcoreio/rubix/lib/Modal.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Modal'>;
}
declare module '@jcoreio/rubix/lib/ModalBody.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/ModalBody'>;
}
declare module '@jcoreio/rubix/lib/ModalDialog.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/ModalDialog'>;
}
declare module '@jcoreio/rubix/lib/ModalFooter.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/ModalFooter'>;
}
declare module '@jcoreio/rubix/lib/ModalHeader.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/ModalHeader'>;
}
declare module '@jcoreio/rubix/lib/ModalTitle.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/ModalTitle'>;
}
declare module '@jcoreio/rubix/lib/Nav.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Nav'>;
}
declare module '@jcoreio/rubix/lib/Navbar.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Navbar'>;
}
declare module '@jcoreio/rubix/lib/NavbarBrand.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/NavbarBrand'>;
}
declare module '@jcoreio/rubix/lib/NavbarCollapse.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/NavbarCollapse'>;
}
declare module '@jcoreio/rubix/lib/NavbarHeader.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/NavbarHeader'>;
}
declare module '@jcoreio/rubix/lib/NavbarToggle.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/NavbarToggle'>;
}
declare module '@jcoreio/rubix/lib/NavDropdown.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/NavDropdown'>;
}
declare module '@jcoreio/rubix/lib/NavItem.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/NavItem'>;
}
declare module '@jcoreio/rubix/lib/Overlay.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Overlay'>;
}
declare module '@jcoreio/rubix/lib/OverlayTrigger.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/OverlayTrigger'>;
}
declare module '@jcoreio/rubix/lib/PageHeader.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/PageHeader'>;
}
declare module '@jcoreio/rubix/lib/PageItem.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/PageItem'>;
}
declare module '@jcoreio/rubix/lib/Pager.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Pager'>;
}
declare module '@jcoreio/rubix/lib/Pagination.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Pagination'>;
}
declare module '@jcoreio/rubix/lib/Panel.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Panel'>;
}
declare module '@jcoreio/rubix/lib/Popover.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Popover'>;
}
declare module '@jcoreio/rubix/lib/Pricing.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Pricing'>;
}
declare module '@jcoreio/rubix/lib/Progress.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Progress'>;
}
declare module '@jcoreio/rubix/lib/ProgressBar.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/ProgressBar'>;
}
declare module '@jcoreio/rubix/lib/ProgressGroup.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/ProgressGroup'>;
}
declare module '@jcoreio/rubix/lib/Radio.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Radio'>;
}
declare module '@jcoreio/rubix/lib/ResponsiveEmbed.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/ResponsiveEmbed'>;
}
declare module '@jcoreio/rubix/lib/Row.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Row'>;
}
declare module '@jcoreio/rubix/lib/RSplitButton.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/RSplitButton'>;
}
declare module '@jcoreio/rubix/lib/SafeAnchor.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/SafeAnchor'>;
}
declare module '@jcoreio/rubix/lib/Sidebar.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Sidebar'>;
}
declare module '@jcoreio/rubix/lib/SplitButton.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/SplitButton'>;
}
declare module '@jcoreio/rubix/lib/SplitHoverButton.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/SplitHoverButton'>;
}
declare module '@jcoreio/rubix/lib/Tab.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Tab'>;
}
declare module '@jcoreio/rubix/lib/TabContainer.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/TabContainer'>;
}
declare module '@jcoreio/rubix/lib/TabContent.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/TabContent'>;
}
declare module '@jcoreio/rubix/lib/Table.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Table'>;
}
declare module '@jcoreio/rubix/lib/TabPane.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/TabPane'>;
}
declare module '@jcoreio/rubix/lib/Tabs.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Tabs'>;
}
declare module '@jcoreio/rubix/lib/Tag.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Tag'>;
}
declare module '@jcoreio/rubix/lib/Thumbnail.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Thumbnail'>;
}
declare module '@jcoreio/rubix/lib/Timeline.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Timeline'>;
}
declare module '@jcoreio/rubix/lib/Tooltip.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Tooltip'>;
}
declare module '@jcoreio/rubix/lib/Well.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/lib/Well'>;
}
declare module '@jcoreio/rubix/src/Accordion.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Accordion'>;
}
declare module '@jcoreio/rubix/src/Alert.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Alert'>;
}
declare module '@jcoreio/rubix/src/AlertLink.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/AlertLink'>;
}
declare module '@jcoreio/rubix/src/Badge.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Badge'>;
}
declare module '@jcoreio/rubix/src/BNavDropdown.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/BNavDropdown'>;
}
declare module '@jcoreio/rubix/src/BPanel.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/BPanel'>;
}
declare module '@jcoreio/rubix/src/BPanelGroup.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/BPanelGroup'>;
}
declare module '@jcoreio/rubix/src/BProgressBar.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/BProgressBar'>;
}
declare module '@jcoreio/rubix/src/Breadcrumb.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Breadcrumb'>;
}
declare module '@jcoreio/rubix/src/BreadcrumbItem.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/BreadcrumbItem'>;
}
declare module '@jcoreio/rubix/src/Button.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Button'>;
}
declare module '@jcoreio/rubix/src/ButtonGroup.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/ButtonGroup'>;
}
declare module '@jcoreio/rubix/src/ButtonToolbar.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/ButtonToolbar'>;
}
declare module '@jcoreio/rubix/src/Carousel.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Carousel'>;
}
declare module '@jcoreio/rubix/src/Checkbox.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Checkbox'>;
}
declare module '@jcoreio/rubix/src/Clearfix.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Clearfix'>;
}
declare module '@jcoreio/rubix/src/Col.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Col'>;
}
declare module '@jcoreio/rubix/src/Collapse.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Collapse'>;
}
declare module '@jcoreio/rubix/src/ControlLabel.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/ControlLabel'>;
}
declare module '@jcoreio/rubix/src/Dispatcher.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Dispatcher'>;
}
declare module '@jcoreio/rubix/src/Dropdown.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Dropdown'>;
}
declare module '@jcoreio/rubix/src/DropdownButton.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/DropdownButton'>;
}
declare module '@jcoreio/rubix/src/DropdownHoverButton.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/DropdownHoverButton'>;
}
declare module '@jcoreio/rubix/src/DropdownMenu.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/DropdownMenu'>;
}
declare module '@jcoreio/rubix/src/DropdownToggle.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/DropdownToggle'>;
}
declare module '@jcoreio/rubix/src/Fade.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Fade'>;
}
declare module '@jcoreio/rubix/src/Form.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Form'>;
}
declare module '@jcoreio/rubix/src/FormControl.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/FormControl'>;
}
declare module '@jcoreio/rubix/src/FormControlFeedback.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/FormControlFeedback'>;
}
declare module '@jcoreio/rubix/src/FormControlStatic.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/FormControlStatic'>;
}
declare module '@jcoreio/rubix/src/FormGroup.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/FormGroup'>;
}
declare module '@jcoreio/rubix/src/Glyphicon.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Glyphicon'>;
}
declare module '@jcoreio/rubix/src/Grid.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Grid'>;
}
declare module '@jcoreio/rubix/src/HelpBlock.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/HelpBlock'>;
}
declare module '@jcoreio/rubix/src/Icon.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Icon'>;
}
declare module '@jcoreio/rubix/src/Image.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Image'>;
}
declare module '@jcoreio/rubix/src/index.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/index'>;
}
declare module '@jcoreio/rubix/src/InputGroup.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/InputGroup'>;
}
declare module '@jcoreio/rubix/src/isBrowser.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/isBrowser'>;
}
declare module '@jcoreio/rubix/src/isTouchDevice.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/isTouchDevice'>;
}
declare module '@jcoreio/rubix/src/Jumbotron.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Jumbotron'>;
}
declare module '@jcoreio/rubix/src/L20n.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/L20n'>;
}
declare module '@jcoreio/rubix/src/Label.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Label'>;
}
declare module '@jcoreio/rubix/src/Lead.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Lead'>;
}
declare module '@jcoreio/rubix/src/ListGroup.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/ListGroup'>;
}
declare module '@jcoreio/rubix/src/ListGroupItem.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/ListGroupItem'>;
}
declare module '@jcoreio/rubix/src/LoremIpsum.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/LoremIpsum'>;
}
declare module '@jcoreio/rubix/src/Media.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Media'>;
}
declare module '@jcoreio/rubix/src/MediaBody.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/MediaBody'>;
}
declare module '@jcoreio/rubix/src/MediaHeading.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/MediaHeading'>;
}
declare module '@jcoreio/rubix/src/MediaLeft.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/MediaLeft'>;
}
declare module '@jcoreio/rubix/src/MediaList.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/MediaList'>;
}
declare module '@jcoreio/rubix/src/MediaListItem.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/MediaListItem'>;
}
declare module '@jcoreio/rubix/src/MediaRight.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/MediaRight'>;
}
declare module '@jcoreio/rubix/src/MenuItem.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/MenuItem'>;
}
declare module '@jcoreio/rubix/src/Modal.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Modal'>;
}
declare module '@jcoreio/rubix/src/ModalBody.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/ModalBody'>;
}
declare module '@jcoreio/rubix/src/ModalDialog.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/ModalDialog'>;
}
declare module '@jcoreio/rubix/src/ModalFooter.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/ModalFooter'>;
}
declare module '@jcoreio/rubix/src/ModalHeader.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/ModalHeader'>;
}
declare module '@jcoreio/rubix/src/ModalTitle.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/ModalTitle'>;
}
declare module '@jcoreio/rubix/src/Nav.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Nav'>;
}
declare module '@jcoreio/rubix/src/Navbar.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Navbar'>;
}
declare module '@jcoreio/rubix/src/NavbarBrand.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/NavbarBrand'>;
}
declare module '@jcoreio/rubix/src/NavbarCollapse.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/NavbarCollapse'>;
}
declare module '@jcoreio/rubix/src/NavbarHeader.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/NavbarHeader'>;
}
declare module '@jcoreio/rubix/src/NavbarToggle.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/NavbarToggle'>;
}
declare module '@jcoreio/rubix/src/NavDropdown.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/NavDropdown'>;
}
declare module '@jcoreio/rubix/src/NavItem.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/NavItem'>;
}
declare module '@jcoreio/rubix/src/Overlay.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Overlay'>;
}
declare module '@jcoreio/rubix/src/OverlayTrigger.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/OverlayTrigger'>;
}
declare module '@jcoreio/rubix/src/PageHeader.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/PageHeader'>;
}
declare module '@jcoreio/rubix/src/PageItem.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/PageItem'>;
}
declare module '@jcoreio/rubix/src/Pager.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Pager'>;
}
declare module '@jcoreio/rubix/src/Pagination.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Pagination'>;
}
declare module '@jcoreio/rubix/src/Panel.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Panel'>;
}
declare module '@jcoreio/rubix/src/Popover.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Popover'>;
}
declare module '@jcoreio/rubix/src/Pricing.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Pricing'>;
}
declare module '@jcoreio/rubix/src/Progress.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Progress'>;
}
declare module '@jcoreio/rubix/src/ProgressBar.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/ProgressBar'>;
}
declare module '@jcoreio/rubix/src/ProgressGroup.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/ProgressGroup'>;
}
declare module '@jcoreio/rubix/src/Radio.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Radio'>;
}
declare module '@jcoreio/rubix/src/ResponsiveEmbed.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/ResponsiveEmbed'>;
}
declare module '@jcoreio/rubix/src/Row.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Row'>;
}
declare module '@jcoreio/rubix/src/RSplitButton.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/RSplitButton'>;
}
declare module '@jcoreio/rubix/src/SafeAnchor.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/SafeAnchor'>;
}
declare module '@jcoreio/rubix/src/Sidebar.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Sidebar'>;
}
declare module '@jcoreio/rubix/src/SplitButton.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/SplitButton'>;
}
declare module '@jcoreio/rubix/src/SplitHoverButton.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/SplitHoverButton'>;
}
declare module '@jcoreio/rubix/src/Tab.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Tab'>;
}
declare module '@jcoreio/rubix/src/TabContainer.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/TabContainer'>;
}
declare module '@jcoreio/rubix/src/TabContent.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/TabContent'>;
}
declare module '@jcoreio/rubix/src/Table.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Table'>;
}
declare module '@jcoreio/rubix/src/TabPane.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/TabPane'>;
}
declare module '@jcoreio/rubix/src/Tabs.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Tabs'>;
}
declare module '@jcoreio/rubix/src/Tag.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Tag'>;
}
declare module '@jcoreio/rubix/src/Thumbnail.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Thumbnail'>;
}
declare module '@jcoreio/rubix/src/Timeline.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Timeline'>;
}
declare module '@jcoreio/rubix/src/Tooltip.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Tooltip'>;
}
declare module '@jcoreio/rubix/src/Well.js' {
  declare module.exports: $Exports<'@jcoreio/rubix/src/Well'>;
}
