exports.REDIS_HOST = 'localhost'
exports.REDIS_PORT = '6379'
exports.DB_HOST = 'localhost'
exports.DB_USER = 'root'
exports.DB_NAME = 'pasonpower'
exports.DB_PASSWORD = 'password'
exports.DYNAMO_ENDPOINT = 'http://localhost:8000'
exports.DYNAMO_TABLE_PREFIX = 'battmanAppDev-'
exports.LOG_GROUP_NAME = 'battmanDataConsumerDevShard'
exports.AWS_REGION = 'us-west-2'
exports.GOOGLE_MAPS_API_KEY = 'AIzaSyCr1k0xWOB3oNS5zbF9hvKNExKEq5aA8ho'
exports.GENABILITY_APP_ID = 'e9f61549-fa11-4710-9dc5-1452dd47c036'
exports.GENABILITY_APP_KEY = 'd0f71985-8c8b-413d-a4f4-5e2863c202ad'
exports.GENABILITY_BASE_URL = 'https://api.genability.com/rest/public'
exports.BATTSIM_BASE_URL = 'http://localhost:5000/battsim'

